### ISSUE TITLE
Error in MessageSet.decode

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#155]
On current master (with a large value for `socket_receive_buffer_bytes` to circumvent #151), I get the following when trying to start a SimpleConsumer:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "pykafka/simpleconsumer.py", line 226, in fetcher
    self.fetch()
  File "pykafka/simpleconsumer.py", line 383, in fetch
    min_bytes=self._fetch_min_bytes
  File "pykafka/broker.py", line 212, in fetch_messages
    return future.get(FetchResponse)
  File "pykafka/handlers.py", line 57, in get
    return response_cls(self.response)
  File "pykafka/protocol.py", line 651, in __init__
    partition[2], self._unpack_message_set(partition[3]),
  File "pykafka/protocol.py", line 658, in _unpack_message_set
    message_set = MessageSet.decode(buff)
  File "pykafka/protocol.py", line 264, in decode
    msg_offset, size = struct.unpack_from('!qi', buff, offset)
error: unpack_from requires a buffer of at least 12 bytes
```
Some poking around shows that `buff` is about a megabyte in size, and the exception occurs when `offset` is 4 bytes from the end. I see this on three different topics, two created by a librdkafka example script, and one created by our pykafka producer - will see if it's reproducible asap.

**Comment by emmett9001** [comment]
This bug happened when there were more messages to consume than the `max_bytes` value supplied in a fetch request. Kafka returned exactly `max_bytes`, cutting off a message in the middle. Thus, the buffer it returned ended up being smaller than the reported length of the message set by the size difference between the length of the message set and `max_bytes`.

This was fixed [here](https://github.com/Parsely/pykafka/commit/ac5fda0d310a6a7f59a9c1b06a36244de99c92aa).

**Comment by yungchin** [comment]
Works great - thanks!!
