### ISSUE TITLE
SocketDisconectedError while trying to start balancedconsumer

### ISSUE THREAD

**Issue by ziky90** [Parsely/pykafka#196]
I keep getting SocketDisconectedError when I am trying to use balancedconsumer. I am able to work with this particular kafka from terminal via scripts, but I am not able to connect it using pykafka. 

My KafkaHandler code looks as follows:
```
class KafkaHandler(threading.Thread):
    daemon = True

    def __init__(self, kafka_path, zookeeper, group=DEF_GROUP, consumer_topic=DEF_TOPIC):
        self.kafka = KafkaClient(hosts=kafka_path)
        topic = self.kafka.topics[consumer_topic]
        self.consumer = topic.get_balanced_consumer(
            consumer_group=group,
            auto_commit_enable=True,
            zookeeper_connect=zookeeper
        )
        self.producer = topic.get_producer()
        super(KafkaHandler, self).__init__()

   def run(self):
        self.process_kafka_messages()
```

I would like to ask if I'm missing something or if there might be some problem in kafka configuration or inside of pykafka.

I went through stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/home/ubuntu/web_scraper/http_server/server.py", line 78, in <module>
    handler = kafka_pipe.KafkaHandler(config.kafka, config.zookeeper, group=config.kafka_group, consumer_topic=config.topic)
  File "/home/ubuntu/web_scraper/kafka_pipes/kafka_pipe.py", line 41, in __init__
    zookeeper_connect=zookeeper
  File "/usr/local/lib/python2.7/dist-packages/pykafka/topic.py", line 156, in get_balanced_consumer
    return BalancedConsumer(self, self._cluster, consumer_group, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pykafka/balancedconsumer.py", line 183, in __init__
    self.start()
  File "/usr/local/lib/python2.7/dist-packages/pykafka/balancedconsumer.py", line 213, in start
    self._rebalance()
  File "/usr/local/lib/python2.7/dist-packages/pykafka/balancedconsumer.py", line 407, in _rebalance
    self._setup_internal_consumer()
  File "/usr/local/lib/python2.7/dist-packages/pykafka/balancedconsumer.py", line 268, in _setup_internal_consumer
    reset_offset_on_start=reset_offset_on_start
  File "/usr/local/lib/python2.7/dist-packages/pykafka/simpleconsumer.py", line 156, in __init__
    self._discover_offset_manager()
  File "/usr/local/lib/python2.7/dist-packages/pykafka/simpleconsumer.py", line 230, in _discover_offset_manager
    self._offset_manager = self._cluster.get_offset_manager(self._consumer_group)
  File "/usr/local/lib/python2.7/dist-packages/pykafka/cluster.py", line 252, in get_offset_manager
    res = future.get(ConsumerMetadataResponse)
  File "/usr/local/lib/python2.7/dist-packages/pykafka/handlers.py", line 55, in get
    raise self.error
SocketDisconnectedError
```

It seems to me that problem is somewhere inside comunication with kafka.

**Comment by kbourgoin** [comment]
This can be a tricky one to debug, but it's something we've seen as well.

One possibility is that this can arise if you're running Kafka in a container like docker or a vagrant VM. The problem is that it sees its hostname as the internal IP to the container, and then gives that to the client when it looks to connect to other brokers.  That is, instead of `localhost:9092` it might give `10.0.0.2:9092`, which may or may not be accessible to the client.  I can't tell based on the stacktrace if that's what's going on, but I know it's happened to us and was fixed by using the `advertised.host.name` Kafka setting so that it was an address which would be accessible.

The only other thing I can think of is to make sure you're up to date on Kafka. We've only extensively tested PyKafka with 0.8.2.1, so I can't guarantee it'll work with anything older.

I think the only way to truly debug this will be to set some logging or breakpoints so that it's clear what it's trying to connect to and being sure that's accessible.  There may also be some log messages in Kafka if the request is getting to the broker. Based on where this happens, that broker connection should already be established, so I'm not sure what's going on.

Looking at this I realize that you setting breakpoints in a client library isn't the most fun. I'm going to make a note to go through PyKafka and add a bunch of debug logging so it's more obvious what it's doing before crashes like this.

**Comment by ziky90** [comment]
To provide the full information, it seems that log on zookeeper is following (I've just replaced ip addresses):
```
2015-06-29 15:09:28,790] INFO Accepted socket connection from /<ip_address>:44113 (org.apache.zookeeper.server.NIOServerCnxn)
[2015-06-29 15:09:28,790] INFO Client attempting to establish new session at /<ip_address>:44113 (org.apache.zookeeper.server.NIOServerCnxn)
[2015-06-29 15:09:28,792] INFO Established session 0x14bfde8e5de027b with negotiated timeout 6000 for client /<ip_address> (org.apache.zookeeper.server.NIOServerCnxn)
[2015-06-29 15:09:28,867] WARN EndOfStreamException: Unable to read additional data from client sessionid 0x14bfde8e5de027b, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn)
[2015-06-29 15:09:28,868] INFO Closed socket connection for client /<ip_address>:44113 which had sessionid 0x14bfde8e5de027b (org.apache.zookeeper.server.NIOServerCnxn)
```

And Kafka log looks as follows (again ip address was replaced and some logs might be related also to other traffic):
```
[2015-06-29 15:09:01,293] INFO Closing socket connection to /<ip_address> due to invalid request: Request of length 825569072 is not valid, it is larger than the maximum size of 104857600 bytes. (kafka.network.Processor)
[2015-06-29 15:09:05,575] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:05,575] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:05,629] INFO Closing socket connection to /<ip_address>(kafka.network.Processor)
[2015-06-29 15:09:05,629] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:05,713] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:05,713] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:06,786] INFO Closing socket connection to /<ip_address>(kafka.network.Processor)
[2015-06-29 15:09:06,886] INFO Closing socket connection to /<ip_address>(kafka.network.Processor)
[2015-06-29 15:09:11,679] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:11,679] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:11,679] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:11,679] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:11,679] INFO Closing socket connection to /<ip_address>. (kafka.network.Processor)
[2015-06-29 15:09:11,679] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:11,679] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:11,679] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:11,680] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:11,680] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
[2015-06-29 15:09:28,817] ERROR Closing socket for /<ip_address> because of error (kafka.network.Processor)
kafka.common.KafkaException: Wrong request type 10
	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:57)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:53)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:745)
[2015-06-29 15:09:28,867] INFO Closing socket connection to /<ip_address> (kafka.network.Processor)
```

**Comment by kbourgoin** [comment]
The `Wrong request type 10` definitely makes me think this is a Kafka version problem. What version are you running?  Request type 10 is for the [offset commit/fetch API](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetCommit/FetchAPI), which in only available in 0.8.2+.

**Comment by ziky90** [comment]
I'm running Kafka 0.8.1 and yes you are right, this is the most likely a problem.
Looking around, it seems that there is no alternative for usage of balanced consumer with Kafka 0.8.1 so the it seems that the only possible solution for me is migrating to Kafka 0.8.2+.?

**Comment by kbourgoin** [comment]
PyKafka is currently the only python driver with a balance consumer implementation, so unfortunately you'd have to upgrade in order to be able to use it.
