### ISSUE TITLE
Cannot import name urllib_parse

### ISSUE THREAD

**Issue by patrickmay** [Parsely/pykafka#222]
I'm trying a simple test of pykafka and get this error:

Traceback (most recent call last):
  File "./pykafka-test.py", line 5, in <module>
    from pykafka import KafkaClient
  File "/usr/local/lib/python2.7/dist-packages/pykafka/__init__.py", line 3, in <module>
    from cluster import Cluster
  File "/usr/local/lib/python2.7/dist-packages/pykafka/cluster.py", line 31, in <module>
    from .topic import Topic
  File "/usr/local/lib/python2.7/dist-packages/pykafka/topic.py", line 23, in <module>
    from .balancedconsumer import BalancedConsumer
  File "/usr/local/lib/python2.7/dist-packages/pykafka/balancedconsumer.py", line 28, in <module>
    from kazoo.client import KazooClient
  File "/usr/local/lib/python2.7/dist-packages/kazoo/client.py", line 25, in <module>
    from kazoo.hosts import collect_hosts
  File "/usr/local/lib/python2.7/dist-packages/kazoo/hosts.py", line 3, in <module>
    from six.moves import urllib_parse
ImportError: cannot import name urllib_parse

**Comment by yungchin** [comment]
You might have an old version of six. What does `pip freeze | grep six` say?

**Comment by patrickmay** [comment]
six==1.9.0

Thanks.

**Comment by kbourgoin** [comment]
I'm not clear, did you upgrade to 1.9.0 and now it works? This is a kazoo issue, so it's annoying that they haven't pinned the version of six in order to prevent this.  If we can figure out which version of six is missing `urllib_parse` then we can file an issue over there.

**Comment by kbourgoin** [comment]
I've got 1.9.0 locally and this is working fine:

    $ python -c "from six.moves import urllib_parse"

**Comment by patrickmay** [comment]
I just installed pykafka with pip and ran the test.  I didn't do anything explicitly with six.

**Comment by kbourgoin** [comment]
Does the above line work for you?  Also, what version of Python are you using?

**Comment by patrickmay** [comment]
I'm using 2.7.3 and that line returns fine.

**Comment by patrickmay** [comment]
Okay, it looks like the error was spurious.  When I came back in this morning my connection to AWS had been dropped.  After logging back in, I no longer get this error.  My apologies for wasting your time.
