### ISSUE TITLE
producer retry regression

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#239]
The retry logic from the old producer hasn't been properly adapted for the new async producer.
```
ERROR:pykafka.producer:Exception encountered in worker thread:
  File "/home/emmett/git/parsely/pykafka/pykafka/producer.py", line 393, in queue_reader
    self.producer._prepare_request(batch, self)
  File "/home/emmett/git/parsely/pykafka/pykafka/producer.py", line 235, in _prepare_request
    self._send_request(request, 0, owned_broker)
  File "/home/emmett/git/parsely/pykafka/pykafka/producer.py", line 318, in _send_request
    self._produce(to_retry, attempt)

INFO:pykafka.producer:Blocking until all messages are sent
Traceback (most recent call last):
  File "../notes/kafka_producer_test.py", line 25, in <module>
    time.sleep(.1)
  File "/home/emmett/git/parsely/pykafka/pykafka/producer.py", line 167, in __exit__
    self.stop()
  File "/home/emmett/git/parsely/pykafka/pykafka/producer.py", line 183, in stop
    self._wait_all()
  File "/home/emmett/git/parsely/pykafka/pykafka/producer.py", line 354, in _wait_all
    self._raise_worker_exceptions()
  File "/home/emmett/git/parsely/pykafka/pykafka/producer.py", line 152, in _raise_worker_exceptions
    raise ex
TypeError: _produce() takes exactly 2 arguments (3 given)
```

**Comment by emmett9001** [comment]
https://github.com/Parsely/pykafka/commit/01d80484a8cf5b52cb9cdc528e45529809ff8e23
