### ISSUE TITLE
Sync producer fails when required_acks == 0

### ISSUE THREAD

**Issue by cscheffler** [Parsely/pykafka#278]
pykafka version: 2.0.0

Behaviour: producing a message fails when a producer is created with `sync=True` and `required_acks=0`. This does not happen with `required_acks=1` (default) or `sync=False` (default).

To reproduce:

    from pykafka import KafkaClient
    kafka_client = KafkaClient(hosts=HOSTS)
    topic = kafka_client.topics[TOPIC]
    message = 'test'
    with topic.get_producer(sync=True, required_acks=0) as producer:
        producer.produce(message)

Exception:

    Traceback (most recent call last):
      File "test.py", line 11, in <module>
        producer.produce(message)
      File "/home/ubuntu/carl/kafka-tests/venv/local/lib/python2.7/site-packages/pykafka/producer.py", line 169, in __exit__
        self.stop()
      File "/home/ubuntu/carl/kafka-tests/venv/local/lib/python2.7/site-packages/pykafka/producer.py", line 219, in stop
        self._wait_all()
      File "/home/ubuntu/carl/kafka-tests/venv/local/lib/python2.7/site-packages/pykafka/producer.py", line 359, in _wait_all
        self._raise_worker_exceptions()
      File "/home/ubuntu/carl/kafka-tests/venv/local/lib/python2.7/site-packages/pykafka/producer.py", line 154, in _raise_worker_exceptions
        raise ex
    AttributeError: 'NoneType' object has no attribute 'topics'

**Comment by yungchin** [comment]
Thanks, this one's confirmed too. Additionally, it's even worse on the producer-futures branch, #269 - there we'd simply block forever (great!).

**Comment by yungchin** [comment]
Quick update: this is also a problem when `sync=False`, it's just that the error doesn't surface in the main thread as readily.
