### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'fetch_lock'

### ISSUE THREAD

**Issue by xqliang** [Parsely/pykafka#335]
```
[ERROR][2015-11-09 18:11:03] simpleconsumer.py 199, Exception encountered in worker thread:
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 318, in fetcher
    self.fetch()
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 668, in fetch
    success_handler=_handle_success)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/utils/error_handlers.py", line 54, in handle_partition_responses
    error_handlers[errcode](parts)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 241, in _handle_OffsetOutOfRangeError
    for owned_partition, pres in parts]
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 603, in reset_offsets
    owned_partition.fetch_lock.release()

[ERROR][2015-11-09 18:11:03] eventhub.py 304, consume error, stop and retry later, topic=dispatch_1025_33 group=None
Traceback (most recent call last):
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/eventhub/eventhub.py", line 296, in _consume
    event = consumer.consume(block=False)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 351, in consume
    self._raise_worker_exceptions()
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 200, in _raise_worker_exceptions
    raise ex
AttributeError: 'tuple' object has no attribute 'fetch_lock'
```

```
Name: pykafka
Version: 2.0.2
```

May be something wrong [here](https://github.com/Parsely/pykafka/blob/master/pykafka/utils/error_handlers.py#L76) .

**Comment by yungchin** [comment]
Ouch, this looks nasty, thanks for reporting it. From a quick inspection I would've thought we have test coverage for this, but clearly it's not good enough.

**Comment by emmett9001** [comment]
@xqliang I'm pretty sure this bug is a simple typo in `reset_offsets` that is only hit rarely. It's a one-line fix, but I'm wondering if you can supply the output you got [here](https://github.com/Parsely/pykafka/blob/2.0.2/pykafka/simpleconsumer.py#L593) - it would help me write a test for this case.

**Comment by emmett9001** [comment]
[This commit](https://github.com/Parsely/pykafka/commit/2b3a9f14880f20649b076da156c00a4aefc2e55a) should do the trick, but I'll leave this ticket open for a test case to make sure this function actually handles error responses properly.

**Comment by xqliang** [comment]
@emmett9001 There are many topics rebalancing, and the following error messages just appears before the AttributeError exception:

```
[ERROR][2015-11-09 18:11:02] simpleconsumer.py 596, Error resetting offsets for topic dispatch_1025_33 (errors: {<class 'pykafka.exceptions.OffsetOutOfRangeError'>: [0]})
[INFO][2015-11-09 18:11:02] balancedconsumer.py 462, Rebalancing consumer onlinegame-229-159:9edc24e7-e6ed-4f91-b2bd-2d0741947bfa for topic dispatch_1025_24.
[INFO][2015-11-09 18:11:02] balancedconsumer.py 462, Rebalancing consumer onlinegame-229-159:da807098-7ce6-42ea-ab62-625ad7f6ebbc for topic dispatch_1025_11.
[INFO][2015-11-09 18:11:02] balancedconsumer.py 365, Balancing 1 participants for 1 partitions.
Owning 1 partitions.
[INFO][2015-11-09 18:11:02] balancedconsumer.py 365, Balancing 1 participants for 1 partitions.
Owning 1 partitions.
[INFO][2015-11-09 18:11:02] cluster.py 282, Attempting to discover offset manager for consumer group 'roomdata'
[INFO][2015-11-09 18:11:02] balancedconsumer.py 500, Rebalancing Complete.
[INFO][2015-11-09 18:11:02] balancedconsumer.py 462, Rebalancing consumer onlinegame-229-159:25a5fa53-7760-452f-abc5-2912454776af for topic dispatch_2_6.
[INFO][2015-11-09 18:11:02] balancedconsumer.py 365, Balancing 1 participants for 1 partitions.
Owning 1 partitions.
[INFO][2015-11-09 18:11:02] balancedconsumer.py 500, Rebalancing Complete.
[ERROR][2015-11-09 18:11:02] eventhub.py 221, start consumer error
Traceback (most recent call last):
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/eventhub/eventhub.py", line 211, in _get_consumer
    consumer.start()
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 243, in start
    self._rebalance()
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 498, in _rebalance
    self._setup_internal_consumer(list(new_partitions))
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 315, in _setup_internal_consumer
    auto_start=start
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 163, in __init__
    self._discover_offset_manager()
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 264, in _discover_offset_manager
    self._offset_manager = self._cluster.get_offset_manager(self._consumer_group)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/cluster.py", line 295, in get_offset_manager
    res = future.get(ConsumerMetadataResponse)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/handlers.py", line 61, in get
    return response_cls(self.response)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/protocol.py", line 907, in __init__
    response = struct_helpers.unpack_from(fmt, buff, 0)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/utils/struct_helpers.py", line 49, in unpack_from
    output = _unpack(fmt, buff, offset, 1)[0]
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/utils/struct_helpers.py", line 96, in _unpack
    items.extend(struct.unpack_from('!' + ch, buff, offset))
error: unpack_from requires a buffer of at least 25705 bytes
[INFO][2015-11-09 18:11:02] balancedconsumer.py 462, Rebalancing consumer onlinegame-229-159:da807098-7ce6-42ea-ab62-625ad7f6ebbc for topic dispatch_1025_11.
[INFO][2015-11-09 18:11:02] balancedconsumer.py 365, Balancing 1 participants for 1 partitions.
Owning 1 partitions.
[INFO][2015-11-09 18:11:02] balancedconsumer.py 500, Rebalancing Complete.
[INFO][2015-11-09 18:11:02] balancedconsumer.py 462, Rebalancing consumer onlinegame-229-159:673ccd23-c390-42fe-bf88-512334ae1107 for topic dispatch_1025_9.
[INFO][2015-11-09 18:11:02] balancedconsumer.py 365, Balancing 1 participants for 1 partitions.
Owning 1 partitions.
[INFO][2015-11-09 18:11:02] balancedconsumer.py 462, Rebalancing consumer onlinegame-229-159:da807098-7ce6-42ea-ab62-625ad7f6ebbc for topic dispatch_1025_11.
[INFO][2015-11-09 18:11:02] cluster.py 282, Attempting to discover offset manager for consumer group 'roomdata'
[INFO][2015-11-09 18:11:03] balancedconsumer.py 365, Balancing 1 participants for 1 partitions.
Owning 1 partitions.
[INFO][2015-11-09 18:11:03] balancedconsumer.py 500, Rebalancing Complete.
[INFO][2015-11-09 18:11:03] balancedconsumer.py 462, Rebalancing consumer onlinegame-229-159:25a5fa53-7760-452f-abc5-2912454776af for topic dispatch_2_6.
[INFO][2015-11-09 18:11:03] balancedconsumer.py 365, Balancing 1 participants for 1 partitions.
Owning 1 partitions.
[INFO][2015-11-09 18:11:03] balancedconsumer.py 500, Rebalancing Complete.
[INFO][2015-11-09 18:11:03] cluster.py 308, Found coordinator broker with id 0
[INFO][2015-11-09 18:11:03] balancedconsumer.py 462, Rebalancing consumer onlinegame-229-159:da807098-7ce6-42ea-ab62-625ad7f6ebbc for topic dispatch_1025_11.
[ERROR][2015-11-09 18:11:03] eventhub.py 221, start consumer error
Traceback (most recent call last):
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/eventhub/eventhub.py", line 211, in _get_consumer
    consumer.start()
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 243, in start
    self._rebalance()
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 498, in _rebalance
    self._setup_internal_consumer(list(new_partitions))
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 315, in _setup_internal_consumer
    auto_start=start
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 182, in __init__
    self.start()
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 222, in start
    self.fetch_offsets()
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 468, in fetch_offsets
    res = self._offset_manager.fetch_consumer_group_offsets(self._consumer_group, reqs)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/broker.py", line 350, in fetch_consumer_group_offsets
    return self._offsets_channel_req_handler.request(req).get(OffsetFetchResponse)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/handlers.py", line 61, in get
    return response_cls(self.response)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/protocol.py", line 1165, in __init__
    response = struct_helpers.unpack_from(fmt, buff, 0)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/utils/struct_helpers.py", line 49, in unpack_from
    output = _unpack(fmt, buff, offset, 1)[0]
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/utils/struct_helpers.py", line 79, in _unpack
    offset + 4, count)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/utils/struct_helpers.py", line 115, in _unpack_array
    item, offset = _unpack(fmt, buff, offset)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/utils/struct_helpers.py", line 79, in _unpack
    offset + 4, count)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/utils/struct_helpers.py", line 115, in _unpack_array
    item, offset = _unpack(fmt, buff, offset)
  File "/home/xqliang/.virtualenvs/room/local/lib/python2.7/site-packages/pykafka/utils/struct_helpers.py", line 96, in _unpack
    items.extend(struct.unpack_from('!' + ch, buff, offset))
error: unpack_from requires a buffer of at least 8 bytes
[INFO][2015-11-09 18:11:03] simpleconsumer.py 325, Starting 1 fetcher threads
[INFO][2015-11-09 18:11:03] eventhub.py 286, retry topic succeed, topic=dispatch_1025_8 group=None
[INFO][2015-11-09 18:11:03] balancedconsumer.py 365, Balancing 1 participants for 1 partitions.
Owning 1 partitions.
[INFO][2015-11-09 18:11:03] balancedconsumer.py 500, Rebalancing Complete.
[INFO][2015-11-09 18:11:03] simpleconsumer.py 375, Autocommitting consumer offset for consumer group roomdata and topic dispatch_2_6
[INFO][2015-11-09 18:11:03] simpleconsumer.py 375, Autocommitting consumer offset for consumer group roomdata and topic dispatch_1025_11
[INFO][2015-11-09 18:11:03] balancedconsumer.py 462, Rebalancing consumer onlinegame-229-159:da807098-7ce6-42ea-ab62-625ad7f6ebbc for topic dispatch_1025_11.
[INFO][2015-11-09 18:11:03] balancedconsumer.py 365, Balancing 1 participants for 1 partitions.
Owning 1 partitions.
[INFO][2015-11-09 18:11:03] balancedconsumer.py 500, Rebalancing Complete.
[INFO][2015-11-09 18:11:03] balancedconsumer.py 462, Rebalancing consumer onlinegame-229-159:25a5fa53-7760-452f-abc5-2912454776af for topic dispatch_2_6.
```

**Comment by emmett9001** [comment]
That's interesting, since there are no calls to `reset_offsets` visible in those call stacks. I suppose we can leave the test until we have more information.
