### ISSUE TITLE
pykafka not compatible with gevent.monkey.patch_socket

### ISSUE THREAD

**Issue by fuellee** [Parsely/pykafka#365]
after `gevent.monkey.patch_socket()` :

    Traceback (most recent call last):
    File "./lbs_info_all.py", line 66, in <module>
        client = KafkaClient(hosts=hosts)
    File "/home/lify/ENV/lib/python2.7/site-packages/pykafka/client.py", line 83, in __init__
        source_address=self._source_address
    File "/home/lify/ENV/lib/python2.7/site-packages/pykafka/cluster.py", line 173, in __init__
        self.update()
    File "/home/lify/ENV/lib/python2.7/site-packages/pykafka/cluster.py", line 315, in update
        metadata = self._get_metadata()
    File "/home/lify/ENV/lib/python2.7/site-packages/pykafka/cluster.py", line 226, in _get_metadata
        'Unable to connect to a broker to fetch metadata. See logs.')
    RuntimeError: Unable to connect to a broker to fetch metadata. See logs.

**Comment by emmett9001** [comment]
Thanks @fuellee. Are you trying to run pykafka in a gevent-managed environment? If so I'm afraid we can't guarantee that it will work properly at the moment. We have a ticket open about supporting this in the future, so maybe this is a push to prioritize that feature. As far as my investigation shows, though, solving this seems to require patching pykafka's socket machinery to directly use `gevent.socket`. If you have any insight into this, please share.

**Comment by emmett9001** [comment]
The pull request for gevent support is in the final testing phase and should hopefully make it into a release by the end of this week.
