### ISSUE TITLE
SimpleProducer with a HashingPartitioner fails under python3

### ISSUE THREAD

**Issue by gth828r** [Parsely/pykafka#366]
When using a HashingPartitioner for a SimpleProducer on a topic with multiple partitions, running under python3 fails with the following stack trace:
```
Traceback (most recent call last):
  File "/vagrant/test.py", line 17, in <module>
    producer.produce(message, key)
  File "/usr/local/lib/python3.4/dist-packages/pykafka-2.0.3-py3.4.egg/pykafka/producer.py", line 244, in produce
    partition_id = self._partitioner(partitions, partition_key).id
  File "/usr/local/lib/python3.4/dist-packages/pykafka-2.0.3-py3.4.egg/pykafka/partitioners.py", line 77, in __call__
    partitions = sorted(partitions)  # sorting is VERY important
TypeError: unorderable types: Partition() < Partition()
```

Passing the list of partition objects to `sorted()` is not an issue in python2.  I assume that this is related to [this issue](http://python3porting.com/problems.html#unorderable-types-cmp-and-cmp).

**Comment by gth828r** [comment]
Just FYI, I was able to get past the stack trace by adding a very basic `__lt__` implementation to the Partition class:
```python
    def __lt__(self, other):
        return hash(self) < hash(other)
```
