### ISSUE TITLE
Error discovering offset manager.

### ISSUE THREAD

**Issue by Daemon22** [Parsely/pykafka#393]
Hi, 

i'm new to kafka and I'm trying to use pykafka in order to talked with my kafka cluster.
I'm trying to run [this demo test](https://github.com/cscheffler/kafka-demo) but with no success.
It looks like it is connecting to the cluster but cannot get the correct offset to the consumer group.

My configuration is like this:
* 3 kafka servers running kafka_2.11-0.8.2.2 (I had 2.11-0.9.0.0 installed before with the same error message)
* 1 zookeeper 3.4.5 server on a different machine.

This is the full log:

2015-12-15 14:27:04,157 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2015-12-15 14:27:04,158 - pykafka.cluster - INFO - Discovered 3 brokers
2015-12-15 14:27:04,189 - pykafka.cluster - INFO - Discovered 2 topics
2015-12-15 14:27:04,197 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2015-12-15 14:27:04,197 - pykafka.topic - INFO - Adding 6 partitions
2015-12-15 14:27:04,203 - kazoo.client - INFO - Connecting to 172.20.0.112:2181
2015-12-15 14:27:04,212 - kazoo.client - INFO - Zookeeper connection established, state: CONNECTED
2015-12-15 14:27:04,239 - pykafka.balancedconsumer - INFO - Rebalancing consumer ubuntu:57f927c8-56a2-4378-b592-b5713568d69e for topic test.
2015-12-15 14:27:04,244 - pykafka.balancedconsumer - INFO - Balancing 1 participants for 6 partitions.
Owning 6 partitions.
2015-12-15 14:27:04,268 - pykafka.cluster - INFO - Attempting to discover offset manager for consumer group 'test_group'
2015-12-15 14:27:04,382 - pykafka.cluster - ERROR - Error discovering offset manager.
2015-12-15 14:27:05,160 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2015-12-15 14:27:05,197 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2015-12-15 14:27:06,403 - pykafka.cluster - ERROR - Error discovering offset manager.
2015-12-15 14:27:10,420 - pykafka.cluster - ERROR - Error discovering offset manager.
2015-12-15 14:27:16,447 - pykafka.cluster - ERROR - Error discovering offset manager.
2015-12-15 14:27:24,475 - pykafka.cluster - ERROR - Error discovering offset manager.
2015-12-15 14:27:24,476 - pykafka.balancedconsumer - ERROR - Stopping consumer in response to error
2015-12-15 14:27:24,481 - kazoo.client - INFO - Closing connection to 172.20.0.112:2181
2015-12-15 14:27:24,481 - kazoo.client - INFO - Zookeeper session lost, state: CLOSED
Exception AttributeError: "'SimpleConsumer' object has no attribute '_partitions'" in <bound method SimpleConsumer.__del__ of <pykafka.simpleconsumer.SimpleConsumer at 0x7fc5a891cfd0 (consumer_group=test_group)>> ignored
Traceback (most recent call last):
  File "/mnt/hgfs/Shared/mercurial/test/pykafka/demo-consumer.py", line 34, in <module>
    message = consumer.consume()  # Read one message from Kafka
  File "/usr/local/lib/python2.7/dist-packages/pykafka/balancedconsumer.py", line 687, in consume
    raise NoPartitionsForConsumerException()
pykafka.exceptions.NoPartitionsForConsumerException
Consuming messagse from topic 'test'. Press Ctrl-C to interrupt.
2015-12-15 14:27:24,489 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2015-12-15 14:27:24,489 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2015-12-15 14:27:24,489 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/local/lib/python2.7/dist-packages/pykafka/handlers.py", line 150, in worker
  File "/usr/lib/python2.7/Queue.py", line 177, in get
  File "/usr/lib/python2.7/threading.py", line 354, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

Please let me know how can I check if this is a configuration error.

**Comment by emmett9001** [comment]
Thanks @Daemon22. I can't replicate this error at the moment, but I do have a related fix out on [this branch](https://github.com/Parsely/pykafka/pull/392). If you'd like, please try testing your code against that branch and see if the result changes. Thanks!

**Comment by Daemon22** [comment]
Thanks, it is working now.
One more thins, do you know if there is and issue with using pykafka on kafka 0.9.0.0?

**Comment by yungchin** [comment]
@Daemon22 pykafka doesn't support any of the new 0.9 features yet, but there shouldn't be any issues running against a 0.9 cluster - tests for current master pass: https://travis-ci.org/Parsely/pykafka/builds/96841207
