### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by JaneVinWin** [Parsely/pykafka#402]
when the code ran for a while, it raised below exception:
```
No handlers could be found for logger "pykafka.simpleconsumer"
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    for message in balanced_consumer:
  File "/usr/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 707, in __iter__
    message = self.consume(block=True)
  File "/usr/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 693, in consume
    message = self._consumer.consume(block=block)
  File "/usr/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 371, in consume
    self._raise_worker_exceptions()
  File "/usr/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 203, in _raise_worker_exceptions
    raise ex
AttributeError: 'NoneType' object has no attribute 'id'
Exception AttributeError: "'NoneType' object has no attribute 'id'" in <bound method BalancedConsumer.__del__ of <pykafka.balancedconsumer.BalancedConsumer at 0x28ec8d0 (consumer_group=test2)>> ignored
```

my code is:
```python
from pykafka import KafkaClient
client = KafkaClient(hosts="XXXXX")
topic = client.topics['topic']
balanced_consumer = topic.get_balanced_consumer(
    consumer_group='test2',
    auto_commit_enable=True,
    num_consumer_fetchers=5,
    reset_offset_on_start=False,
    fetch_message_max_bytes=1048576*10,
    zookeeper_connect='XXXXX')
for message in balanced_consumer:
    if message is not None:
        print "offset: " + str(message.offset)
    else: 
        pass
```

**Comment by emmett9001** [comment]
@JaneVinWin thanks! There should be another traceback a bit farther up in the error log that indicates the original location of the exception - you've posted the one corresponding to the re-raising of the error on the main thread. Is there any way you can supply the original exception? Without that it's a bit tough to guess what the issue is, since your demo code is very standard.

**Comment by JaneVinWin** [comment]
@emmett9001 i don't understand what it the original exception. i've already posted all exception i've got.

**Comment by tigran-a** [comment]
I think if you add this code
```python
import logging
logging.root.level = logging.INFO
kafkalogger= logging.getLogger('pykafka')
kazoologger= logging.getLogger('kazoo')
console_handler = logging.StreamHandler()
console_handler.setFormatter(formatter)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
console_handler.setLevel(logging.INFO)
kafkalogger.addHandler(console_handler)
kazoologger.addHandler(console_handler)
```
right after line 
```
from pykafka import KafkaClient
```
and run the code again to get the exception, it will output more information to the console

**Comment by JaneVinWin** [comment]
@tigran-a i just did as you said, then i got below msg:
2015-12-28 20:16:08,707 - pykafka.simpleconsumer - ERROR - Exception encountered in worker thread:
 File "/usr/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 314, in autocommitter
    self._auto_commit()
  File "/usr/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 397, in _auto_commit
    self.commit_offsets()
  File "/usr/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 410, in commit_offsets
    self._offset_manager.id)

Traceback (most recent call last):
  File "test.py", line 20, in <module>
    for message in balanced_consumer:
  File "/usr/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 707, in __iter__
    message = self.consume(block=True)
  File "/usr/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 693, in consume
    message = self._consumer.consume(block=block)
  File "/usr/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 371, in consume
    self._raise_worker_exceptions()
  File "/usr/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 203, in _raise_worker_exceptions
    raise ex
AttributeError: 'NoneType' object has no attribute 'id'
Exception AttributeError: "'NoneType' object has no attribute 'id' in <bound method BalancedConsumer.__del__ of <pykafka.balancedconsumer.BalancedConsumer at 0xe0c990 (consumer_group=test2)>> ignored

**Comment by emmett9001** [comment]
Interesting - the `_offset_manager` is being unset for some reason.The only apparent way this is possible is if the consumer is created without a `consumer_group` kwarg, but you're supplying one in your example code. Is it possible that somewhere in your application you're introducing some variability into the value of `_consumer_group`, or some situation in which it could be `None` during consumer initialization?

**Comment by JaneVinWin** [comment]
@emmett9001 i remembered one thing, when i killed my previous process and then restarted the same code with the same groupid, it failed most of the time. So that i have to change a new group id.

**Comment by jofusa** [comment]
not that I'm going to make this any less hazy but we are seeing the same error:

```AttributeError: 'NoneType' object has no attribute 'id'
  File "vip_filter/worker.py", line 93, in <module>
    worker.process_stream()
  File "pykafkaworker/worker.py", line 54, in process_stream
    self._report_offsets(message)
  File "pykafkaworker/worker.py", line 93, in _report_offsets
    self._consumer.commit_offsets()
  File "pykafka/balancedconsumer.py", line 720, in commit_offsets
    return self._consumer.commit_offsets()
  File "pykafka/simpleconsumer.py", line 410, in commit_offsets
    self._offset_manager.id)```

**Comment by gerrickw** [comment]
I am able to reproduce this issue with the latest git kafka_tools.py cli script.

**Comment by emmett9001** [comment]
@gerrickw @jofusa @JaneVinWin Does anyone have any error logs including any of the logging messages from [this loop](https://github.com/Parsely/pykafka/blob/781b49f8f45e87c864d2ff5e474e926c6f41d415/pykafka/cluster.py#L350)? A failure to discover the offset manager seems like the most likely culprit to me.
