### ISSUE TITLE
How to use pykafka.balancedconsumer reset_offsets function

### ISSUE THREAD

**Issue by daiguadaidai** [Parsely/pykafka#417]
Hi !
I use balancedconsumer reset_offsets function, but get ERROR. What should I do?
My customer Code is:
```
from pykafka import KafkaClient
client = KafkaClient(hosts="192.168.137.11:9092")
topic = client.topics['test']
balanced_consumer = topic.get_balanced_consumer(
  consumer_group='test_group',
  auto_commit_enable=True,
  zookeeper_connect='localhost:2181'
)
for message in balanced_consumer:
  if message is not None:
    print message.offset, message.value
```
output:
```
1 Message 1
2 Message 2
3 Message 4
5 Message 5
6 Message 6
7 Message 7
.......
```
use reset_offsets function Code:
```
balanced_consumer.reset_offsets(partition_offsets=(balanced_consumer.partitions[0], 1))
```
ERROR:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Canopy_64bit/User/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 671, in reset_offsets
    self._consumer.reset_offsets(partition_offsets=partition_offsets)
  File "/usr/local/Canopy_64bit/User/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 591, in reset_offsets
    for p, offset in partition_offsets}
  File "/usr/local/Canopy_64bit/User/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 590, in <dictcomp>
    owned_partition_offsets = {self._partitions[p]: offset
TypeError: 'Partition' object is not iterable
```

**Comment by emmett9001** [comment]
Hi @daiguadaidai. `reset_offsets` accepts a sequence of tuples, and you've given it a single tuple. You can fix your code by changing it to
```python
balanced_consumer.reset_offsets(partition_offsets=[(balanced_consumer.partitions[0], 1)])
```
Notice the square brackets around the argument. The [documentation](http://pykafka.readthedocs.org/en/latest/api/simpleconsumer.html#pykafka.simpleconsumer.SimpleConsumer.reset_offsets) for `reset_offsets` does indicate that this function accepts an iterable, but I suppose it could be more clear.

**Comment by daiguadaidai** [comment]
Hi @emmett9001 you are right.
it's helpful for me.
thanks!
