### ISSUE TITLE
Extra messages between topics...

### ISSUE THREAD

**Issue by waypointsoftware** [Parsely/pykafka#481]
PyKafka version: 2.2.1
Kafka version: .8.2

I have a situation where I posted in 40k messages to a topic, I verify with the offset checker utility that 40k messages are indeed in the topic (which has 16 partitions).

I then start up a consumer process that consumes these 40k and puts them in another topic. This processes uses 4 threads and the balanced consumer to consume. 

What I am seeing is a variable number of messages actually making it to the 2nd topic. Usually sometimes in the ballpark of 38k but each time I get a different amount and I cant track down where its happening, below is the log output that maybe someone can look at and tell me why I am seeing these? They arent on every message but its somewhat frequent.

```
Mar 07 15:46:29 localhost.localdomain ironwood-zookeeper[25697]: Closed socket connection for client /127.0.0.1:45562 which had sessionid 0x15351b633be00c3
Mar 07 15:46:29 localhost.localdomain ironwood-zookeeper[25697]: caught end of stream exception
Mar 07 15:46:29 localhost.localdomain ironwood-zookeeper[25697]: Closed socket connection for client /127.0.0.1:45561 which had sessionid 0x15351b633be00c2
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: Closing socket for /127.0.0.1 because of error
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: [2016-03-07 15:46:29,725] INFO Closing socket connection to /127.0.0.1. (kafka.network.Processor)
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: [2016-03-07 15:46:29,725] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: java.io.IOException: Connection reset by peer
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: at sun.nio.ch.IOUtil.read(IOUtil.java:197)
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: at kafka.utils.Utils$.read(Utils.scala:380)
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: at kafka.network.BoundedByteBufferReceive.readFrom(BoundedByteBufferReceive.scala:54)
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: at kafka.network.Processor.read(SocketServer.scala:444)
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: at kafka.network.Processor.run(SocketServer.scala:340)
Mar 07 15:46:29 localhost.localdomain ironwood-kafka[25817]: at java.lang.Thread.run(Thread.java:745)
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Expiring session 0x15351b633be00c9, timeout of 10000ms exceeded
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Expiring session 0x15351b633be00c8, timeout of 10000ms exceeded
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Processed session termination for sessionid: 0x15351b633be00c9
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Processed session termination for sessionid: 0x15351b633be00c8
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Accepted socket connection from /127.0.0.1:45576
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Client attempting to establish new session at /127.0.0.1:45576
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Established session 0x15351b633be00d1 with negotiated timeout 10000 for client /127.0.0.1:45576
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Accepted socket connection from /127.0.0.1:45577
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Client attempting to establish new session at /127.0.0.1:45577
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Established session 0x15351b633be00d2 with negotiated timeout 10000 for client /127.0.0.1:45577
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Accepted socket connection from /127.0.0.1:45578
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Client attempting to establish new session at /127.0.0.1:45578
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Established session 0x15351b633be00d3 with negotiated timeout 6000 for client /127.0.0.1:45578
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Got user-level KeeperException when processing sessionid:0x15351b633be00d3 type:create cxid:0x20 zxid:0x705 txntype:-1 reqpath:n/a Error Path:/consumers/rav-message-enrichment-transformer/owners/rav-event-log-raw/0-8 Error:KeeperErrorCode = NodeExists for /consumers/rav-message-enrichment-transformer/owners/rav-event-log-raw/0-8
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Got user-level KeeperException when processing sessionid:0x15351b633be00d3 type:create cxid:0x39 zxid:0x70a txntype:-1 reqpath:n/a Error Path:/consumers/rav-message-enrichment-transformer/owners/rav-event-log-raw/0-9 Error:KeeperErrorCode = NodeExists for /consumers/rav-message-enrichment-transformer/owners/rav-event-log-raw/0-9
Mar 07 15:46:30 localhost.localdomain ironwood-zookeeper[25697]: Got user-level KeeperException when processing sessionid:0x15351b633be00c7 type:create cxid:0x141 zxid:0x70d txntype:-1 reqpath:n/a Error Path:/consumers/rav-message-enrichment-transformer/owners/rav-event-log-raw/0-2 Error:KeeperErrorCode = NodeExists for /consumers/rav-message-enrichment-transformer/owners/rav-event-log-raw/0-2
```

**Comment by emmett9001** [comment]
Hi @waypointsoftware, thank you for filing this. Do you mind posting the code you're using to consume from the first topic and produce to the second?

**Comment by waypointsoftware** [comment]
http://pastebin.com/wVxp7vzz

**Comment by waypointsoftware** [comment]
I believe we have resolved the "missing message" problem, but we continue to have an "extra message" problem. We send over 40k messages and somehow 40k + [1,2,3,4,5,6, or so] extra messages end up in our second topic.

Here is the theory:

Typically we start up 4 processes from our main consumer script. There are 16 partitions on the topic we are consuming. We are thinking that the process goes something like this:

Process A starts up and takes ownership of partitions 0-15 and begins consuming
Process B starts up and some rebalancing mechanism kicks off giving Process B partitions 0-7 and and Process A partitions 8-15 (just an example)
....so on and so on for Process C and D

We think that during this rebalancing process that a handful of messages are slipping through to other processes because their respective offsets havent updated yet.

If you reference the code in the link, it would be somewhere between "for message in consumer:" and "consumer.commit_offsets()" where this extra message problem happens. 

Does this sound like a plausible theory?

**Comment by emmett9001** [comment]
@waypointsoftware Your theory sounds plausible, but I can't verify it without spending a bit of time digging into the code around rebalancing.

**Comment by emmett9001** [comment]
The behavior @waypointsoftware describes matches Kafka's philosophy of delivering each message at least once, so I'm inclined to declare this not an issue and move on.
