### ISSUE TITLE
Identical KafkaClient is created in different process

### ISSUE THREAD

**Issue by lucidfrontier45** [Parsely/pykafka#491]
Hi all. I'm working on Simple Task worker that contains a Kafka consumer.
My code is as follows.

```python
om multiprocessing import Process

from pykafka import KafkaClient


class KafkaWorker(Process):
    def __init__(self):
        Process.__init__(self)

    def run(self):
        print("{} start".format(self.pid))

        c = KafkaClient(hosts="127.0.0.1:9091")
        print("{}'s client id = {}".format(self.pid, id(c)))
        topic = c.topics["test"]
        consumer = topic.get_balanced_consumer(consumer_group='testgroup',
                                               auto_commit_enable=True,
                                               zookeeper_connect="127.0.0.1:2281")
        for msg in consumer:
            print(self.pid, msg.value)


w1 = KafkaWorker()
w1.start()
w2 = KafkaWorker()
w2.start()
```
When I run this code, it says

```python
13452 start
13453 start
13452's client id = 139805036298320
13453's client id = 139805036298320
No handlers could be found for logger "pykafka.balancedconsumer"
Process KafkaWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/du/PycharmProjects/BusyBee/examples/kafka_test.py", line 19, in run
    for msg in consumer:
  File "/home/du/.virtualenvs/busybee/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 722, in __iter__
    message = self.consume(block=True)
  File "/home/du/.virtualenvs/busybee/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 711, in consume
    raise ConsumerStoppedException
ConsumerStoppedException
```
You can see the two KafkaClient instances have the same id and one of the consumers gives `ConsumerStoppedException`.

What is the right way to include KafkaClient in a Process?  

**Python version**: 2.7,
**PyKafka version**: 2.2.1
**Kafka version**: 0.9.0.1"

**Comment by lucidfrontier45** [comment]
sorry, I used browser's back button and accidentally resubmitted.
