### ISSUE TITLE
KeyError: 22 when rebalancing using ManagedBalancedConsumer

### ISSUE THREAD

**Issue by messense** [Parsely/pykafka#515]
**PyKafka version**: 2.3.0
**Kafka version**: 0.9.0

```
2016-03-30 13:51:03,182 ERROR 22
Traceback (most recent call last):
  File "/Users/messense/workspace/bosondata/brm-index/lib/python2.7/site-packages/pykafka/managedbalancedconsumer.py", line 287, in _update_member_assignment
    partitions=[self._topic.partitions[pid] for pid in assignment[0][1]])
  File "/Users/messense/workspace/bosondata/brm-index/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 355, in _setup_internal_consumer
    cns = self._get_internal_consumer(partitions=list(partitions), start=start)
  File "/Users/messense/workspace/bosondata/brm-index/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 386, in _get_internal_consumer
    self._consumer.stop()
  File "/Users/messense/workspace/bosondata/brm-index/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 339, in stop
    self.commit_offsets()
  File "/Users/messense/workspace/bosondata/brm-index/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 469, in commit_offsets
    partitions_by_id=self._partitions_by_id)
  File "/Users/messense/workspace/bosondata/brm-index/lib/python2.7/site-packages/pykafka/utils/error_handlers.py", line 50, in handle_partition_responses
    error_handlers[errcode](parts)
KeyError: 22
```

Seems like ``IllegalGeneration`` exception did not get handled here.

**Comment by messense** [comment]
Sure.
