### ISSUE TITLE
need help for an error 

### ISSUE THREAD

**Issue by ruiaylin** [Parsely/pykafka#519]
I meet this error , in my application , and i have no idea about that . 

 self.producerList[top].produce(msg)
  File "/usr/lib/python2.7/site-packages/pykafka-2.2.2_dev-py2.7.egg/pykafka/producer.py", line 309, in produce
    self._raise_worker_exceptions()
  File "/usr/lib/python2.7/site-packages/pykafka-2.2.2_dev-py2.7.egg/pykafka/producer.py", line 176, in _raise_worker_exceptions
    raise ex
error: unpack_from requires a buffer of at least 27756 bytes

by the way ,
   producer = tmp_top.get_producer(linger_ms=10)

who can help me ?

**Comment by emmett9001** [comment]
Hi @ruiaylin, thanks for reporting this. It looks likely to be a bug internal to pykafka, but it's hard to be sure. What version of pykafka are you running? Can you supply a larger traceback? There may be another trace a bit farther back in the log that provides more information.

**Comment by ruiaylin** [comment]
@emmett9001  Thanks for the reply . my version is pykafka==2.2.2.dev0 . Exception arise in my code , this is the whole content about the execption : like below 

2016-04-05 08:41:08 LDA INFO [HEALTHD   ]: exec _checkThread()
2016-04-05 08:41:21 LDA ERROR [DUMPTHD   ]: send_message() exception Traceback (most recent call last):
  File "logdumpagent.py", line 377, in send_message
    self.producerList[top].produce(msg)
  File "/usr/lib/python2.7/site-packages/pykafka-2.2.2_dev-py2.7.egg/pykafka/producer.py", line 309, in produce
    self._raise_worker_exceptions()
  File "/usr/lib/python2.7/site-packages/pykafka-2.2.2_dev-py2.7.egg/pykafka/producer.py", line 176, in _raise_worker_exceptions
    raise ex
error: unpack_from requires a buffer of at least 4 bytes

2016-04-05 08:41:21 LDA ERROR [DUMPTHD   ]: send_message() exception unpack_from requires a buffer of at least 4 bytes
2016-04-05 08:41:21 LDA ERROR [DUMPTHD   ]: send_message() exception Traceback (most recent call last):
  File "logdumpagent.py", line 377, in send_message
    self.producerList[top].produce(msg)
  File "/usr/lib/python2.7/site-packages/pykafka-2.2.2_dev-py2.7.egg/pykafka/producer.py", line 309, in produce
    self._raise_worker_exceptions()
  File "/usr/lib/python2.7/site-packages/pykafka-2.2.2_dev-py2.7.egg/pykafka/producer.py", line 176, in _raise_worker_exceptions
    raise ex
error: unpack_from requires a buffer of at least 27756 bytes

sometimes  like this : 

2016-04-05 08:51:38 LDA ERROR [DUMPTHD   ]: send_message() exception Traceback (most recent call last):
  File "logdumpagent.py", line 377, in send_message
    self.producerList[top].produce(msg)
  File "/usr/lib/python2.7/site-packages/pykafka-2.2.2_dev-py2.7.egg/pykafka/producer.py", line 309, in produce
    self._raise_worker_exceptions()
  File "/usr/lib/python2.7/site-packages/pykafka-2.2.2_dev-py2.7.egg/pykafka/producer.py", line 176, in _raise_worker_exceptions
    raise ex
error: unpack_from requires a buffer of at least 4 bytes

2016-04-05 08:51:38 LDA ERROR [DUMPTHD   ]: send_message() exception unpack_from requires a buffer of at least 4 bytes
2016-04-05 08:51:38 LDA ERROR [DUMPTHD   ]: send_message() exception Traceback (most recent call last):
  File "logdumpagent.py", line 377, in send_message
    self.producerList[top].produce(msg)
  File "/usr/lib/python2.7/site-packages/pykafka-2.2.2_dev-py2.7.egg/pykafka/producer.py", line 309, in produce
    self._raise_worker_exceptions()
  File "/usr/lib/python2.7/site-packages/pykafka-2.2.2_dev-py2.7.egg/pykafka/producer.py", line 176, in _raise_worker_exceptions
    raise ex
error: unpack_from requires a buffer of at least 4 bytes

And i really don't know how to fix this .

**Comment by ruiaylin** [comment]
Another thing i don't mention is that two machine with different version of pykafka  . The one with pykafka==2.3.0 have  no error and the other one with pykafka==2.2.2.dev0 has . 

I think the reason of the error maybe caused by the version , i will change the version to run the app again. 

i will give the result later .

**Comment by emmett9001** [comment]
@ruiaylin Sounds good. Please test with the latest version `2.3.0` and let us know if there are still problems.

**Comment by emmett9001** [comment]
@ruiaylin I'm closing this issue - please comment here if you find that upgrading to the latest version hasn't solved your problem.
