### ISSUE TITLE
balanced_consumer ConsumerStoppedException

### ISSUE THREAD

**Issue by hxxgy** [Parsely/pykafka#574]
hi,
I have some troubles when i use balanced_consumer to get msg..
code is like this:
```python
    client = KafkaClient(hosts=Config.brokerList)
        topic = client.topics[Config.topic]
        consumer = topic.get_balanced_consumer(
            consumer_group='testgroup',
            auto_commit_enable=True,
            zookeeper_connect=Config.zookeeperList,
            consumer_timeout_ms=5000
        )
        msgs = []
        while True:
            msg = consumer.consume()
            if (msg == None):
                return msgs
            print(str(msg.offset) + ":" + msg.value)
            #msgs.append(msg)
```
       
when it runs on "consumer.consume()",it raise the exception:ConsumerStoppedException

so, hope someone tell me what's wrong with it... thx

**Comment by emmett9001** [comment]
Hi @hxxgy. Please ensure that the zookeeper and broker hosts you're supplying are accessible from the machine you're running this code on. The `ConsumerStoppedException` is expected from the `consume()` call every once in a while, but if you're encountering it on every call, it's likely that you have something misconfigured. It could also be a bug in pykafka, but other instances of this problem I've seen have been misconfigurations. Also, please test with the most recent version of pykafka.

**Comment by lolandkidtress** [comment]
I met the same problem.
_➜  temp pip freeze  
pykafka==2.4.0._

when changed the code to get_simple_consumer(),my code works well
my code looks like this:
_balanced_consumer = topic.get_balanced_consumer(
	consumer_group='infogen_yunying_topic_job_create',
	auto_commit_enable=False,
	zookeeper_connect='172.16.1.150:2181,172.16.1.151:2181,172.16.1.152:2181'
	)

for message in balanced_consumer:
	if message is not None:
		print message.offset, message.value_

and exception looks like this:
_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 742, in __iter__
    message = self.consume(block=True)
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 731, in consume
    raise ConsumerStoppedException
pykafka.exceptions.ConsumerStoppedException_

**Comment by hxxgy** [comment]
hey, @emmett9001 thanks for your response...  
seems someone else also has the same question. @lolandkidtress 
the version of pykafka I used is 2.4.0, and if i used simple_consumer, the code works fine..
but as you know, simple_consumer can't set the consumer-group, so it's not meet my demand
i also try kaka-python which can set consumer-group，it works fine too...  
so i'm confused...

**Comment by emmett9001** [comment]
@hxxgy Do you have any additional log output you can provide? To get more complete output from pykafka, you can add this code to the top of your test script:

```python
    import logging
    kafkalogger = logging.getLogger('pykafka')
    kafkalogger.setLevel(logging.DEBUG)
    console_handler = logging.StreamHandler()
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    console_handler.setFormatter(formatter)
    console_handler.setLevel(logging.DEBUG)
    kafkalogger.addHandler(console_handler)
```
Without additional log output it will be very difficult to solve your issue. Thanks!

**Comment by woisnow** [comment]
2016-08-05 23:48:26,778 - pykafka.cluster - INFO - Attempting to discover offset manager for consumer group 'test_group'
2016-08-05 23:48:26,806 - pykafka.cluster - ERROR - Error discovering offset manager.
2016-08-05 23:48:26,808 - pykafka.cluster - ERROR - Error discovering offset manager.
2016-08-05 23:48:26,811 - pykafka.cluster - ERROR - Error discovering offset manager.
2016-08-05 23:48:26,814 - pykafka.cluster - ERROR - Error discovering offset manager.
2016-08-05 23:48:26,814 - pykafka.cluster - DEBUG - Retrying offset manager discovery
2016-08-05 23:48:27,739 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2016-08-05 23:48:27,752 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2016-08-05 23:48:28,823 - pykafka.cluster - ERROR - Error discovering offset manager.
2016-08-05 23:48:28,823 - pykafka.cluster - DEBUG - Retrying offset manager discovery
2016-08-05 23:48:30,841 - pykafka.cluster - ERROR - Error discovering offset manager.
2016-08-05 23:48:30,842 - pykafka.cluster - DEBUG - Retrying offset manager discovery
2016-08-05 23:48:32,845 - pykafka.cluster - ERROR - Error discovering offset manager.
2016-08-05 23:48:32,845 - pykafka.cluster - DEBUG - Retrying offset manager discovery
2016-08-05 23:48:34,880 - pykafka.cluster - ERROR - Error discovering offset manager.
2016-08-05 23:48:34,880 - pykafka.cluster - DEBUG - Retrying offset manager discovery
2016-08-05 23:48:38,889 - pykafka.cluster - ERROR - Error discovering offset manager.
2016-08-05 23:48:38,890 - pykafka.balancedconsumer - ERROR - Stopping consumer in response to error
Traceback (most recent call last):
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/balancedconsumer.py", line 306, in start
    self._rebalance()
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/balancedconsumer.py", line 603, in _rebalance
    self._update_member_assignment()
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/balancedconsumer.py", line 578, in _update_member_assignment
    if self._setup_internal_consumer(new_partitions):
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/balancedconsumer.py", line 359, in _setup_internal_consumer
    cns = self._get_internal_consumer(partitions=list(partitions), start=start)
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/balancedconsumer.py", line 417, in _get_internal_consumer
    consumer_id=self._consumer_id
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/rdkafka/simple_consumer.py", line 62, in __init__
    super(RdKafkaSimpleConsumer, self).__init__(**callargs)
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/simpleconsumer.py", line 190, in __init__
    self._discover_group_coordinator()
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/simpleconsumer.py", line 326, in _discover_group_coordinator
    self._group_coordinator = self._cluster.get_group_coordinator(self._consumer_group)
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/cluster.py", line 394, in get_group_coordinator
    res = future.get(GroupCoordinatorResponse)
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/handlers.py", line 72, in get
    return response_cls(self.response)
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/protocol.py", line 929, in __init__
    self.raise_error(error_code, response)
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/protocol.py", line 122, in raise_error
    clsname, response))
GroupCoordinatorNotAvailable: Response Type: "GroupCoordinatorResponse"	Response: (15, -1, '', -1)
2016-08-05 23:48:38,891 - pykafka.balancedconsumer - DEBUG - Stopping <pykafka.balancedconsumer.BalancedConsumer at 0x7fc99a29b750 (consumer_group=test_group)>
2016-08-05 23:48:38,895 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.rdkafka.simple_consumer.RdKafkaSimpleConsumer at 0x7fc99a2cd050 (consumer_group=test_group)>
Traceback (most recent call last):
  File "test2.py", line 26, in <module>
    for message in balanced_consumer:
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/balancedconsumer.py", line 745, in __iter__
    message = self.consume(block=True)
  File "/usr/local/lib64/python2.7/site-packages/pykafka-2.4.1.dev2-py2.7-linux-x86_64.egg/pykafka/balancedconsumer.py", line 734, in consume
    raise ConsumerStoppedException
pykafka.exceptions.ConsumerStoppedException
2016-08-05 23:48:39,901 - pykafka.balancedconsumer - DEBUG - Finalising <pykafka.balancedconsumer.BalancedConsumer at 0x7fc99a29b750 (consumer_group=test_group)>
2016-08-05 23:48:39,901 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2016-08-05 23:48:39,901 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2016-08-05 23:48:39,901 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2016-08-05 23:48:39,901 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue

**Comment by leizhu** [comment]
@hxxgy  I encounter the same error.
How did you fix this issue?

**Comment by hxxgy** [comment]
thanks for all replies..
I fix this issue by upgrading the version of kafka...  
i met this issue when i used version 0.8..
when i upgrade to 1.0, everything is ok  
hope useful for any guys..
