### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by Lowpower** [Parsely/pykafka#589]
```
>>> from pykafka import KafkaClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pykafka/__init__.py", line 1, in <module>
    from .broker import Broker
  File "pykafka/broker.py", line 26, in <module>
    from .protocol import (
  File "pykafka/protocol.py", line 1342
    self.members = {_id: meta for _id, meta in response[5]}
                                ^
SyntaxError: invalid syntax
```

**Comment by Lowpower** [comment]
python version 2.6.6

**Comment by emmett9001** [comment]
Hi @lowpower. Unfortunately, pykafka does not support python 2.6. It only works with python 2.7 and above.
