### ISSUE TITLE
unpack_from requires a buffer of at least `xxx` bytes

### ISSUE THREAD

**Issue by messense** [Parsely/pykafka#598]
I am using current master code.

I have a consumer consuming message from one Kafka topic, when some events occurred, it triggers a pure Python producer to produce some messages to another topic.

Traceback:

``` python
Traceback (most recent call last):
  File "/home/brm_index/venv/local/lib/python2.7/site-packages/brm_index/workers/base.py", line 140, in index_bulk
    to_index = self.map_docs(docs, source)
  File "/home/brm_index/venv/local/lib/python2.7/site-packages/brm_index/workers/basic.py", line 134, in map_docs
    self.on_mapped(body)
  File "/home/brm_index/venv/local/lib/python2.7/site-packages/brm_index/workers/basic.py", line 218, in on_mapped
    k: body.get(k) for k in self.relation_keys
  File "/home/brm_index/venv/local/lib/python2.7/site-packages/brm_index/workers/base.py", line 348, in schedule_relation
    json_util.dumps(message, ensure_ascii=False).encode('utf-8'))
  File "/home/brm_index/venv/local/lib/python2.7/site-packages/pykafka/producer.py", line 350, in produce
    self._raise_worker_exceptions()
  File "/home/brm_index/venv/local/lib/python2.7/site-packages/pykafka/producer.py", line 204, in _raise_worker_exceptions
    raise ex
error: unpack_from requires a buffer of at least 27949 bytes
```

It seems that the producer can't restore to normal state after the exception, causing the process hanging.

**PyKafka version**: @b2ca8eb
**Kafka version**: 0.9.0

**Comment by emmett9001** [comment]
Thanks @messense. I've seen this before, but I haven't been able to reproduce it reliably. It may have something to do with a lack of available memory.

**Comment by emmett9001** [comment]
@messense do you have additional logs from before the traceback? There should be another traceback just before this one in the logs that shows where in the worker thread this error originated.

**Comment by messense** [comment]
@emmett9001 No, no traceback logs from before the traceback.

**Comment by messense** [comment]
I changed to rdkafka based producer and it works good for now.

But I think the cause of this is some network connections got stucked as we have a lot of API requests in our program and some of them didn't set timeout policy.

**Comment by emmett9001** [comment]
@messense Though I can't prove it, I think this may be caused by a lack of available memory in your python interpreter. This seems to jibe with your description of hung API requests.

**Comment by amontalenti** [comment]
I don't think this has to do with memory, @emmett9001. And, we're seeing this issue in production at Parse.ly now, so re-opening the issue.

**Comment by nsf-remoter** [comment]
I have the same problem，maybe you can increase the "fetch_message_max_bytes", in pykafka/utils/struct_helpers.py:_unpack() function, `items.extend(struct.unpack_from('!' + ch, buff, offset))` raise the problem, i find increase `fetch_message_max_bytes` maybe increase the buff length.

**Comment by hbbtstar** [comment]
I'm able to reproduce this reliably with the following code:

https://gist.github.com/hbbtstar/f3663299f12f97de170369c49a2f1d54

The traceback I get from that code is this:

```
Traceback (most recent call last):
  File "get_random_crawled_urls.py", line 22, in <module>
    msg = consumer.consume()
  File "/home/alourenco/pykafka/pykafka/simpleconsumer.py", line 483, in consume
    self._raise_worker_exceptions()
  File "/home/alourenco/pykafka/pykafka/simpleconsumer.py", line 276, in _raise_worker_exceptions
    reraise(*self._worker_exception)
  File "/home/alourenco/.pyenv/versions/3.6.6/envs/casterisk-realtime3/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/alourenco/pykafka/pykafka/simpleconsumer.py", line 440, in fetcher
    self.fetch()
  File "/home/alourenco/pykafka/pykafka/simpleconsumer.py", line 804, in fetch
    min_bytes=self._fetch_min_bytes
  File "/home/alourenco/pykafka/pykafka/broker.py", line 45, in wrapped
    return fn(self, *args, **kwargs)
  File "/home/alourenco/pykafka/pykafka/broker.py", line 327, in fetch_messages
    return future.get(response_class, broker_version=self._broker_version)
  File "/home/alourenco/pykafka/pykafka/handlers.py", line 76, in get
    return response_cls(self.response, **response_kwargs)
  File "/home/alourenco/pykafka/pykafka/protocol/fetch.py", line 216, in __init__
    broker_version=broker_version)
  File "/home/alourenco/pykafka/pykafka/protocol/fetch.py", line 157, in __init__
    response = struct_helpers.unpack_from(fmt, buff, offset)
  File "/home/alourenco/pykafka/pykafka/utils/struct_helpers.py", line 49, in unpack_from
    output = _unpack(fmt, buff, offset, 1)[0]
  File "/home/alourenco/pykafka/pykafka/utils/struct_helpers.py", line 79, in _unpack
    offset + 4, count)
  File "/home/alourenco/pykafka/pykafka/utils/struct_helpers.py", line 115, in _unpack_array
    item, offset = _unpack(fmt, buff, offset)
  File "/home/alourenco/pykafka/pykafka/utils/struct_helpers.py", line 96, in _unpack
    items.extend(struct.unpack_from('!' + ch, buff, offset))
struct.error: unpack_from requires a buffer of at least 24951 bytes
```

The machine in question has about 6GB of RAM free at the moment, so as far as I can tell it's not a memory issue.

**Comment by hbbtstar** [comment]
Also, as an aid, I logged out the ch offset, and buff variables when the exception occurs:

```
ch is 24951s                                                                                                                                                                                                                                 
offset is 10                                                                                                                                                                                                                                 
bytearray(b'\x00\x00\x00\x01\x00\rcrawled_items\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x05P\xaaf\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x07\xfc\x0c\x88\x00\x00\x01\x9b\x00\x00\x00\x00\x07\xfc\x0c\x87\x00\x00\x01\x8f;w\xfd\xea\x00\x02\xff\xff\xff\xff\x00\x00\x01\x81\x82SNAPPY\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x01m\xbb\x05\xf0H\x00\x00\x00\x00\x07\xfc\x0c\x87\x00\x00\x02\xaf\x8f\x8f\x91\xad\x00\x00\xff\xff\xff\xff\x00\x00\x02\xa1{"apikey": "herald-review.com", "canonical_url"\x01&\x1cttps://h>.\x00\xf0r/business/dewitt-county-board-gives-wind-farm-developer-a-victory/article_651e6817-0674-5648-b818-195661ee1aaf.html\x01\xa14response_link"\xfe\xa1\x00\xfe\xa1\x00J\xa1\x00<diff": [["change\x01\xb59V\x14hash64\x01\x14(TrmItu39Ttg>\x0f\x00\x08], f>\x00\x01-\x14Ea9br1\x1d\np]], "ts": 1535018309026, "url\x01\x17\x04["\xfe\xc9\x01\xfe\xc9\x012\xc9\x01\x01\xafPcontent_type": "url"}\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x05U4\xfd\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x05v\xc6?\x00\x00\x00\x00\x00\x00\x00\x00')  
```

the ch string there seems weird to me- from the struct docs, that means we're trying to unpack a 29451 byte string? that seems huge to me, but I'm only dimly knowledgeable about the whole struct / memoryview business.

**Comment by dan-blanchard** [comment]
This happens after I reset offsets using our little helper script.

```pytb
Traceback (most recent call last):
  File "/data/virtualenvs/casterisk/bin/reset_offsets", line 11, in <module>
    load_entry_point('casterisk', 'console_scripts', 'reset_offsets')()
  File "/data/apps/cogtree/builds/casterisk/20180824_00_633ee536ce/casterisk/scripts/reset_offsets.py", line 49, in main
    log.debug("First message returned %s", consumer.consume().value)
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/simpleconsumer.py", line 477, in consume
    self._raise_worker_exceptions()
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/simpleconsumer.py", line 274, in _raise_worker_exceptions
    reraise(*self._worker_exception)
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/simpleconsumer.py", line 439, in fetcher
    self.fetch()
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/simpleconsumer.py", line 831, in fetch
    min_bytes=self._fetch_min_bytes
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/broker.py", line 45, in wrapped
    return fn(self, *args, **kwargs)
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/broker.py", line 327, in fetch_messages
    return future.get(response_class, broker_version=self._broker_version)
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/handlers.py", line 76, in get
    return response_cls(self.response, **response_kwargs)
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/protocol.py", line 1137, in __init__
    broker_version=broker_version)
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/protocol.py", line 1078, in __init__
    response = struct_helpers.unpack_from(fmt, buff, offset)
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/utils/struct_helpers.py", line 49, in unpack_from
    output = _unpack(fmt, buff, offset, 1)[0]
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/utils/struct_helpers.py", line 79, in _unpack
    offset + 4, count)
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/utils/struct_helpers.py", line 115, in _unpack_array
    item, offset = _unpack(fmt, buff, offset)
  File "/data/virtualenvs/casterisk/lib/python3.6/site-packages/pykafka/utils/struct_helpers.py", line 96, in _unpack
    items.extend(struct.unpack_from('!' + ch, buff, offset))
struct.error: unpack_from requires a buffer of at least 25966 bytes
```

**Comment by emmett9001** [comment]
The code triggering @dan-blanchard's traceback above
```python
for topic_name in settings['kafka']['topics'].values():
        topic = kafka_client.topics[topic_name]
        offset = OffsetType.LATEST if args['--offset'] == "latest" else OffsetType.EARLIEST
        consumer_group = settings['kafka']['consumer_group']

        log.info("Resetting topic: %s and consumer group:%s to %s", topic_name,
                 consumer_group, offset)
        log.info("Please stop your topology prior to running, otherwise you will "
                 "have to run again")

        consumer = topic.get_simple_consumer(consumer_group=consumer_group,
                                             auto_offset_reset=offset,
                                             reset_offset_on_start=True)

        log.debug("First message returned %s", consumer.consume().value)
```

**Comment by emmett9001** [comment]
I ran into this today during some Kafka experimentation, and after a lot of digging, learned that both my case and the cases described above are simply results of using the wrong `broker_version` kwarg on `KafkaClient` (rather, not specifying it, since it defaults to `0.9.0`). Neither of the above examples specify this argument. As a result, the decoding logic for `FetchResponse` is treating the beginning of the response buffer as `ThrottleTime`, a newly added field in `0.9.0`, instead of what it actually is when the cluster is `0.8.2`: the length of the `Topics` array. This mistake causes all fields to be misread during decoding, which causes our traceback when it tries to treat some random payload data as a string length.

Since the actual fix is to use the API as defined, I've added a helpful error message in https://github.com/Parsely/pykafka/pull/866. cc @dan-blanchard @hbbtstar

**Comment by taolei0108** [comment]
Thanks @emmett9001 . I made the same mistake today. You reminded me that it could be the KafkaClient version that caused this error. My kafka version is 0.8.2.2 and the default specified broker version for KafkaClient is 0.9.0. So I'm trying to add a parameter broker_version to specify that the broker version is 0.8.2.2. Finally, I succeeded and did not report such mistakes again.

It looks like this
`client = KafkaClient(hosts="10.13.1.25:9092,10.13.1.24:9092",broker_version='0.8.2.2')`

**Comment by YouAreMyLove** [comment]
> Thanks @emmett9001 . I made the same mistake today. You reminded me that it could be the KafkaClient version that caused this error. My kafka version is 0.8.2.2 and the default specified broker version for KafkaClient is 0.9.0. So I'm trying to add a parameter broker_version to specify that the broker version is 0.8.2.2. Finally, I succeeded and did not report such mistakes again.
> 
> It looks like this
> `client = KafkaClient(hosts="10.13.1.25:9092,10.13.1.24:9092",broker_version='0.8.2.2')`
it can solve my problem.  thanks

**Comment by sorintudor** [comment]
Hi,

We are currently trying to take the consumer groups info using the following basic code:

`config = SslConfig(cafile='/home/kafka/caroot.pem', certfile='/home/kafka/client.pem', keyfile='key.pem', password='passwd')
client = KafkaClient(hosts="kafkahost:9093", ssl_config=config, broker_version='2.4.0')
def describe_groups(client):
    client.cluster.get_managed_group_descriptions()

describe_groups(client)`

and it returns the following trace

`Traceback (most recent call last):
  File "kafkaconsumer.py", line 46, in <module>
    describe_groups(client)
  File "kafkaconsumer.py", line 44, in describe_groups
    client.cluster.get_managed_group_descriptions()
  File "/usr/local/lib/python3.6/dist-packages/pykafka/cluster.py", line 428, in get_managed_group_descriptions
    in itervalues(broker.list_groups().groups)])
  File "/usr/local/lib/python3.6/dist-packages/pykafka/broker.py", line 45, in wrapped
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pykafka/broker.py", line 561, in describe_groups
    return future.get(DescribeGroupsResponse)
  File "/usr/local/lib/python3.6/dist-packages/pykafka/handlers.py", line 76, in get
    return response_cls(self.response, **response_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pykafka/protocol/admin.py", line 144, in __init__
    member_info[3])
  File "/usr/local/lib/python3.6/dist-packages/pykafka/protocol/base.py", line 168, in from_bytestring
    response = struct_helpers.unpack_from(fmt, buff, 0)
  File "/usr/local/lib/python3.6/dist-packages/pykafka/utils/struct_helpers.py", line 49, in unpack_from
    output = _unpack(fmt, buff, offset, 1)[0]
  File "/usr/local/lib/python3.6/dist-packages/pykafka/utils/struct_helpers.py", line 79, in _unpack
    offset + 4, count)
  File "/usr/local/lib/python3.6/dist-packages/pykafka/utils/struct_helpers.py", line 115, in _unpack_array
    item, offset = _unpack(fmt, buff, offset)
  File "/usr/local/lib/python3.6/dist-packages/pykafka/utils/struct_helpers.py", line 96, in _unpack
    items.extend(struct.unpack_from('!' + ch, buff, offset))
struct.error: unpack_from requires a buffer of at least 21589 bytes
`
The version of python that we are using is 3.6.9 and also the version of pykafka is 2.8.0

If there are any suggestions, that would be greatly appreciated.

Tnx
