### ISSUE TITLE
pykafka fails to handle failed brokers

### ISSUE THREAD

**Issue by jianbin-wei** [Parsely/pykafka#600]
In pykafka, it asks for metadata from kafka broker, which returns all brokers.  If one broker has issue, pykafka bails out completely even if that broker is not serving any topic/partition.

```
>>> c = pykafka.KafkaClient(hosts="kafka01:9092")
DEBUG:pykafka.cluster:Updating cluster, attempt 1/3
INFO:pykafka.cluster:netskope: connecting to broker kafka01:9092.
DEBUG:pykafka.connection:Connecting to kafka01:9092
DEBUG:pykafka.connection:Successfully connected to kafka01:9092
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 4 brokers
DEBUG:pykafka.cluster:Discovered broker id 1: kafka01:9092
DEBUG:pykafka.connection:Connecting to kafka01:9092
DEBUG:pykafka.connection:Successfully connected to kafka01:9092
DEBUG:pykafka.cluster:Discovered broker id 2: kafka02:9092
DEBUG:pykafka.connection:Connecting to kafka02:9092
DEBUG:pykafka.connection:Successfully connected to kafka02:9092
DEBUG:pykafka.cluster:Discovered broker id 3: kafka03:9092
DEBUG:pykafka.connection:Connecting to kafka03:9092
DEBUG:pykafka.connection:Successfully connected to kafka03:9092
DEBUG:pykafka.cluster:Discovered broker id 7: kafka07:9092
DEBUG:pykafka.connection:Connecting to kafka07:9092
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ns/nsenv/local/lib/python2.7/site-packages/pykafka/client.py", line 94, in __init__
    ssl_config=ssl_config)
  File "/opt/ns/nsenv/local/lib/python2.7/site-packages/pykafka/cluster.py", line 199, in __init__
    self.update()
  File "/opt/ns/nsenv/local/lib/python2.7/site-packages/pykafka/cluster.py", line 425, in update
    self._update_brokers(metadata.brokers)
  File "/opt/ns/nsenv/local/lib/python2.7/site-packages/pykafka/cluster.py", line 352, in _update_brokers
    ssl_config=self._ssl_config)
  File "/opt/ns/nsenv/local/lib/python2.7/site-packages/pykafka/broker.py", line 149, in from_metadata
    ssl_config=ssl_config)
  File "/opt/ns/nsenv/local/lib/python2.7/site-packages/pykafka/broker.py", line 97, in __init__
    self.connect()
  File "/opt/ns/nsenv/local/lib/python2.7/site-packages/pykafka/broker.py", line 211, in connect
    self._connection.connect(self._socket_timeout_ms)
  File "/opt/ns/nsenv/local/lib/python2.7/site-packages/pykafka/connection.py", line 169, in connect
    (self.source_host, self.source_port)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
```

**PyKafka version**: 2.4.0
**Kafka version**: 0.8.2.1

**Comment by emmett9001** [comment]
Hi @jianbin-wei. Please try replicating this bug with [`2.4.1.dev1`](https://github.com/Parsely/pykafka/compare/2.4.0...2.4.1.dev1#diff-0cd1195342277fd8102b19fe6854447eR164), it's been fixed there.

**Comment by jianbin-wei** [comment]
yes verified it works in 2.5.0.dev
