### ISSUE TITLE
Logging error or endless blocking

### ISSUE THREAD

**Issue by smartweka** [Parsely/pykafka#624]
Hi there,
First of all I would like to than you for pykafka - it makes my work much easier.
I have a very strange problem, and it appears only on some of the machines I'm using.
So I have a class that handles producer. In I create a producer attribute like this:
```python
self.producer = self.topic.get_sync_producer(max_request_size=max_request_size)
```
Sending data is done by a simple method:
```python
def save(self, data):
    self.producer.produce(data)
```
This producer handler is used in a loop, sending chunks of some data.
Now, the problem is that when there is no data, program freezes with logging message:
`2016-12-06 13:12:22 [DEBUG] "Blocking until all messages are sent"`
I tried to fix this problem by forcing producer (or rather brokers) to shutdown in a destructor method of my handler:
```python
def __del__(self):
    if self.producer._owned_brokers is not None:
            for owned_broker in self.producer._owned_brokers is not None:
                owned_broker.stop()
```
wchich is a code piece copied from pykafka producer finalizing code (https://github.com/Parsely/pykafka/blob/master/pykafka/producer.py#L287).
Now for the funny part. This code actually stops my program from freezing, but sometimes (and I don't know why not always) it produces a logging error. The data is already sent, but this makes handling this program much more difficult:
```
2016-12-08 14:38:00 [DEBUG] Finalising <pykafka.producer.Producer at 0x7fe44ead9ba8>
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python3.4/logging/__init__.py", line 1045, in emit
    self.stream = self._open()
  File "/usr/lib/python3.4/logging/__init__.py", line 1035, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
  File "/usr/lib/python3.4/encodings/__init__.py", line 98, in search_function
    level=0)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2155, in _find_spec
TypeError: 'NoneType' object is not iterable
Call stack:
  File "/home/pm/.local/lib/python3.4/site-packages/pykafka-2.5.1.dev0-py3.4-linux-x86_64.egg/pykafka/producer.py", line 190, in __del__
    log.debug("Finalising {}".format(self))
Message: 'Finalising <pykafka.producer.Producer at 0x7fe44ead9ba8>'
Arguments: ()
2016-12-08 14:38:00 [INFO] Blocking until all messages are sent
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python3.4/logging/__init__.py", line 1045, in emit
    self.stream = self._open()
  File "/usr/lib/python3.4/logging/__init__.py", line 1035, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
  File "/usr/lib/python3.4/encodings/__init__.py", line 98, in search_function
    level=0)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2155, in _find_spec
TypeError: 'NoneType' object is not iterable
Call stack:
  File "/home/pm/.local/lib/python3.4/site-packages/pykafka-2.5.1.dev0-py3.4-linux-x86_64.egg/pykafka/producer.py", line 191, in __del__
    self.stop()
  File "/home/pm/.local/lib/python3.4/site-packages/pykafka-2.5.1.dev0-py3.4-linux-x86_64.egg/pykafka/producer.py", line 295, in stop
    stop_owned_brokers()
  File "/home/pm/.local/lib/python3.4/site-packages/pykafka-2.5.1.dev0-py3.4-linux-x86_64.egg/pykafka/producer.py", line 288, in stop_owned_brokers
    self._wait_all()
  File "/home/pm/.local/lib/python3.4/site-packages/pykafka-2.5.1.dev0-py3.4-linux-x86_64.egg/pykafka/producer.py", line 492, in _wait_all
    log.info("Blocking until all messages are sent")
Message: 'Blocking until all messages are sent'
Arguments: ()
```
Maybe you can help me figure out what is going on. I know it is a long shot, as I can't replicate logging error every time/on every machine, and I can't send you much more code I'm using. But any help will be appreciated.

I'm using pykafka build using this commit hash:
**PyKafka version**: c7e3dc767d1628ddcdd46964d371eab42cbbfe93
**Kafka version**: 0.9
**Python version**: 3.4.5
**OS**: Ubuntu 12.04

**Comment by emmett9001** [comment]
Hi @smartweka, and thanks for the detailed issue report. I'm glad you're getting some good use out of pykafka.

What do you mean exactly by "when there is no data, program freezes"? It sounds like you might be letting your client program exit as soon as it's done with whatever processing it's doing. If that's the case, you'll probably want to call `Producer.stop()` before your program exits. Also, I don't know for sure, but I have a hunch that the logging errors you're seeing are related to the producer attempting to finalize itself during the python interpreter's shutdown sequence. Some of the modules necessary to do proper logging may already have been unloaded, causing the strange `TypeError`s you're seeing from `importlib`.

You might also benefit from adapting the solution @rogaha used [here](https://github.com/Parsely/pykafka/issues/352#issuecomment-156488199) - it ensures that `Producer.stop()` is always called before interpreter shutdown.

**Comment by smartweka** [comment]
Yes, you are right! Now I'm explicitly destroying producer (`del self.producer`) just after sending stops - when there is no more data to send. Program now exits without problems.
