### ISSUE TITLE
Broken pipe exception

### ISSUE THREAD

**Issue by yjpu** [Parsely/pykafka#637]
Hi,
 My pykafka version 2.4.0, and kafka version is 0.9.0.0.
 Our system got so many "Broken pipe" exception:
```
[2016-08-11 10:40:40,918][140595995432768-MainThread][ERROR]<kafka_producer_client.py:103> send exception: [Errno 32] Broken pipe
 Traceback (most recent call last):
 File "/home/itest/scorpio_job/common/kafka/kafka_producer_client.py", line 96, in send
 producer.produce(message)
 File "/usr/local/lib/python2.7/site-packages/pykafka/producer.py", line 341, in produce
 self._raise_worker_exceptions()
 File "/usr/local/lib/python2.7/site-packages/pykafka/producer.py", line 202, in _raise_worker_exceptions
 raise ex
 error: [Errno 32] Broken pipe
```

I find a same issue done here! 
I did like you say:
```
try:
    consumer.consume()
except IOError:
    consumer.stop()
    consumer.start()
```
by the way I use asynchronous because of the large num.

but here is the question like you say:
1.sometimes it success if i do this
2.sometimes it will fail all the time, no matter how many times i try this.

but if I release KafkaClient,Producer object and rebuild the KafkaClient object , 'Broken pipe' problem all gone.but in this  situation,maybe I will lose my meesage that not be send.

Would you please to deal with this 'Broken pipe Exception', in that way,we will not lose the messages to be sended in you 'get_delivery_report' or any other Solution in asynchronous.
Thank you!^_^

**Comment by hallelujah-shih** [comment]
my pykafka version is 2.5.0, has the same bug!!!
```
producer:203 Exception encountered in worker thread:#012  
File "/usr/lib/python2.7/dist-packages/pykafka/producer.py", line 541, in queue_reader#012    self.producer._send_request(batch, self)#012  
File "/usr/lib/python2.7/dist-packages/pykafka/producer.py", line 421, in _send_request#012          response = owned_broker.broker.produce_messages(req)#012  
File "/usr/lib/python2.7/dist-packages/pykafka/broker.py", line 296, in produce_messages#012    return future.get(ProduceResponse)#012  File "/usr/lib/python2.7/dist-packages/pykafka/handlers.py", line 70, in get#012    raise self.error
```

**Comment by emmett9001** [comment]
@yjpu @hallelujah-shih please give [this branch](https://github.com/Parsely/pykafka/pull/640) a try and let me know how it affects the errors you're seeing.
