### ISSUE TITLE
how to solve this java.io.IOException when use pykafka productor

### ISSUE THREAD

**Issue by wobuxiangtong** [Parsely/pykafka#675]
```
[2017-04-05 18:41:54,269] WARN Resetting first dirty offset to log start offset 349536 since the checkpointed offset 861 is invalid. (kafka.log.LogCleanerManager$)
[2017-04-05 18:41:54,269] WARN Resetting first dirty offset to log start offset 132 since the checkpointed offset 118 is invalid. (kafka.log.LogCleanerManager$)
[2017-04-05 18:41:54,269] WARN Resetting first dirty offset to log start offset 999 since the checkpointed offset 218 is invalid. (kafka.log.LogCleanerManager$)
[2017-04-05 18:42:09,270] WARN Resetting first dirty offset to log start offset 349536 since the checkpointed offset 861 is invalid. (kafka.log.LogCleanerManager$)
[2017-04-05 18:42:09,270] WARN Resetting first dirty offset to log start offset 132 since the checkpointed offset 118 is invalid. (kafka.log.LogCleanerManager$)
[2017-04-05 18:42:09,270] WARN Resetting first dirty offset to log start offset 999 since the checkpointed offset 218 is invalid. (kafka.log.LogCleanerManager$)
[2017-04-05 18:42:17,444] WARN [ReplicaFetcherThread-0-1], Error in fetch kafka.server.ReplicaFetcherThread$FetchRequest@3ec79d08 (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 1 was disconnected before the response was read
        at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1$$anonfun$apply$1.apply(NetworkClientBlockingOps.scala:115)
        at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1$$anonfun$apply$1.apply(NetworkClientBlockingOps.scala:112)
        at scala.Option.foreach(Option.scala:257)
        at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1.apply(NetworkClientBlockingOps.scala:112)
        at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1.apply(NetworkClientBlockingOps.scala:108)
        at kafka.utils.NetworkClientBlockingOps$.recursivePoll$1(NetworkClientBlockingOps.scala:137)
        at kafka.utils.NetworkClientBlockingOps$.kafka$utils$NetworkClientBlockingOps$$pollContinuously$extension(NetworkClientBlockingOps.scala:143)
        at kafka.utils.NetworkClientBlockingOps$.blockingSendAndReceive$extension(NetworkClientBlockingOps.scala:108)
        at kafka.server.ReplicaFetcherThread.sendRequest(ReplicaFetcherThread.scala:253)
        at kafka.server.ReplicaFetcherThread.fetch(ReplicaFetcherThread.scala:238)
        at kafka.server.ReplicaFetcherThread.fetch(ReplicaFetcherThread.scala:42)
        at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:118)
        at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:103)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
```

**Comment by emmett9001** [comment]
Hi @wobuxiangtong. Please provide some example python code that can be used to reliably trigger this error, as well as indications of what versions of python, kafka, and pykafka you're using. Thanks!

**Comment by wobuxiangtong** [comment]
1.demo code as below:
# coding=utf-8
from pykafka import KafkaClient,SslConfig
import time
# config= SslConfig(cafile="/usr/local/kafka/ssl/client.truststore.jks", certfile="/usr/local/kafka/ssl/client.keystore.jks", keyfile="/usr/local/kafka/ssl/ca-key", password="server-70")
# client = KafkaClient(
#     hosts="server-70:9091, server-70:9092, server-70:9093",ssl_config=config)
# client = KafkaClient(
#     hosts="139.129.237.240:9092, 139.129.237.241:9092, 139.129.238.1:9093")
topic = client.topics[b'uni']


def kafka_producer():
    # with topic.get_sync_producer(min_queued_messages=1000,auto_start=False,) as producer:
    with topic.get_producer(min_queued_messages=1000,auto_start=False,sync=False) as producer:
        while True:
            producer.start()
            for i in range(1, 100):
                for j in range(1, 100):
                    kafka_str=('test message ' + str(i) + ":" + str(j))
                    print(kafka_str)
                    producer.produce(kafka_str.encode("utf-8",'ignore'))
            producer.stop()
if __name__ == '__main__':
    kafka_producer()

2. I use python3.5,kafka2.11-0.10.1.0,I am not sure the pykafka version，I just  installed it with pip3. thanks for your reply。

**Comment by emmett9001** [comment]
@wobuxiangtong I'm guessing that calling `producer.start()` and `producer.stop()` on every `while True` iteration is causing you problems. These calls create and destroy multiple threads, some of which may be in the process of talking to the broker when `stop()` is called. I recommend removing the `stop` and `start` calls from your code and seeing what changes.

**Comment by emmett9001** [comment]
Looks like you're hitting [this](https://issues.apache.org/jira/browse/KAFKA-4477), which is a bug in the broker, not pykafka.
