### ISSUE TITLE
Weakly referenced object no longer exists

### ISSUE THREAD

**Issue by kariya2** [Parsely/pykafka#676]
I have a very simple consumer, producer model with producer initiated with (min_queued = 1, sync= False) and consumer with (consumergroup,auto_commit = True, fetch_min = 1). 
My consumer is only consuming messages when the producer is run with pdb or strace for some reason and on occasion throws the error shown below.

this implentation used to work before, but it is now non deterministically failing. Any help would be appreciated 

Exception in thread 3: pykafka.OwnedBroker.queue_reader for broker 0:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/pykafka/producer.py", line 544, in queue_reader
    self.producer._worker_exception = sys.exc_info()
ReferenceError: weakly-referenced object no longer exists

**Comment by kariya2** [comment]
sorry realised this is a duplicate. Added atexit which seems to fix it
