### ISSUE TITLE
 BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by ShichaoMa** [Parsely/pykafka#703]
I'd like to know why this error heppen when I use it in scrapy pipiline.
here is the code

```
def async_produce_wrapper(producer, logger):
    count = 0

    def wrapper(func):

        def inner(*args, **kwargs):
            result = func(*args, **kwargs)
            nonlocal count
            count += 1
            if count % 10 == 0:  # adjust this or bring lots of RAM ;)
                while True:
                    try:
                        msg, exc = producer.get_delivery_report(block=False)
                        if exc is not None:
                            logger.error('Failed to deliver msg {}: {}'.format(
                                msg.partition_key, repr(exc)))
                        else:
                            logger.info('Successfully delivered msg {}'.format(
                                msg.partition_key))
                    except Empty:
                        break
            return result
        return inner
    return wrapper


kafka = KafkaClient("192.168.200.140:9092,192.168.200.141:9092,192.168.200.142:9092")
producer = kafka.topics[b"jay_firehose_ingress"].get_producer(delivery_reports=True)
producer.produce = async_produce_wrapper(producer, logger)(producer.produce)
.......
.......
.......
producer.produce(message.encode("utf-8"))
````
here is the error
```
b'error heppend in pipline Traceback (most recent call last):'
b' File "/app/crawling/pipelines.py", line 76, in process_item'
b' self.producer.produce(message.encode("utf-8"))'
b' File "/app/crawling/spiders/utils.py", line 47, in inner'
b' result = func(*args, **kwargs)'
b' File "/usr/local/lib/python3.6/site-packages/pykafka/producer.py", line 350, in produce'
b' self._raise_worker_exceptions()'
b' File "/usr/local/lib/python3.6/site-packages/pykafka/producer.py", line 204, in _raise_worker_exceptions'
b' raise ex'
[above repeats >100 times]
b' File "/usr/local/lib/python3.6/site-packages/pykafka/producer.py", line 541, in queue_reader'
b' self.producer._send_request(batch, self)'
b' File "/usr/local/lib/python3.6/site-packages/pykafka/producer.py", line 421, in _send_request'
b' response = owned_broker.broker.produce_messages(req)'
b' File "/usr/local/lib/python3.6/site-packages/pykafka/broker.py", line 296, in produce_messages'
b' return future.get(ProduceResponse)'
b' File "/usr/local/lib/python3.6/site-packages/pykafka/handlers.py", line 70, in get'
b' raise self.error'
b' File "/usr/local/lib/python3.6/site-packages/pykafka/handlers.py", line 205, in worker'
b' shared.connection.request(task.request)'
b' File "/usr/local/lib/python3.6/site-packages/pykafka/connection.py", line 198, in request'
b' self._socket.sendall(bytes_)'
b'BrokenPipeError: [Errno 32] Broken pipe'
```

I wonder why the error message is so long and repeat many times,

I start 30 docker container to run this code. 

how to avoid this error?

my English is pool, I hope you can know my meaning. thanks. 

**PyKafka version**: 2.5.0
**Kafka version**: 0.10.1.0

**Comment by emmett9001** [comment]
@ShichaoMa Thanks for filing this! I'm guessing that the reason the error message is repeating so many times has something to do with the environment under which you're running this code, so it's difficult to comment on without having more context. As for the error itself, this appears very similar to an error the connection code is already [aware of](https://github.com/Parsely/pykafka/blob/3d6bad524d152029d0a77481a728ad4973769d7a/pykafka/connection.py#L199). We might want to handle `BrokenPipeError` here as well.

**Comment by cnaafhvk** [comment]
I guess the count of docker container/kafka connection may cause this error. When I reduce the docker container count from 30 to 15, error missed. But still can't find the reason.
