### ISSUE TITLE
ImportError: cannot import name _rd_kafka

### ISSUE THREAD

**Issue by dzmhust** [Parsely/pykafka#721]
When I run, prompt for the following error， how can i resolve this problem。
```
2017-09-13 15:08:30 [pykafka.topic] INFO: Could not load pykafka.rdkafka extension.
2017-09-13 15:08:30 [pykafka.topic] DEBUG: Traceback:
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\pykafka\topic.py", line 39, in <module>
    from . import rdkafka
  File "D:\Python27\lib\site-packages\pykafka\rdkafka\__init__.py", line 1, in <module>
    from .producer import RdKafkaProducer
  File "D:\Python27\lib\site-packages\pykafka\rdkafka\producer.py", line 7, in <module>
    from . import _rd_kafka
ImportError: cannot import name _rd_kafka
```

**Comment by emmett9001** [comment]
@dzmhust What version of the python interpreter are you running under, and how did you install pykafka?

**Comment by dzmhust** [comment]
python2.7.12
