### ISSUE TITLE
Type Error in client.topics

### ISSUE THREAD

**Issue by Juntaran** [Parsely/pykafka#759]
Error:

```
INFO:pykafka.cluster:Discovered 3 brokers
INFO:pykafka.cluster:Discovered 46 topics
Traceback (most recent call last):
  File "/Users/juntaran/workspace/pyWorkspace/kafkaTest/kafkaTest.py", line 16, in <module>
    topic = client.topics["test"]
  File "/Users/juntaran/test/lib/python3.6/site-packages/pykafka/cluster.py", line 56, in __getitem__
    "got '%s'", type(key))
TypeError: ("TopicDict.__getitem__ accepts a bytes object, but it got '%s'", <class 'str'>)
```

Here is my code:

```python
client = KafkaClient(hosts="docker155:9092,docker156:9092,docker157:9092")
topic = client.topics["test"]

cosumer = topic.get_simple_consumer(consumer_timeout_ms=10000)
cnt = 0
for message in cosumer:
	if message is not None:
		print(message.offset, message.value)
	cnt += 1
	print(cnt)
```

Please help me, thanks

**Comment by emmett9001** [comment]
@Juntaran `client.topics` has keys that are `bytes`, not `str`. You need to pass a `bytes` object like so:
```python
topic = client.topics[b"test"]
```
#405 tracks the possibility of adding support for python3 unicode strings.
