### ISSUE TITLE
NoNodeError on commit offset using 2.7.0-dev2

### ISSUE THREAD

**Issue by rodrabe** [Parsely/pykafka#761]
I have 3 consumers reading the same topic with 120 partitions.
Only one of the three consumers failed;  however the lag for the topic increased.
Restarting the consumer worked.

Looks like we are getting a NoNodeError when trying to commit offsets:

```
Traceback (most recent call last):
  File "/Metrics-Transformation-Service/code_dir/consumer.py", line 476, in run
    self._process_messages(partitions)
  File "/Metrics-Transformation-Service/code_dir/consumer.py", line 522, in _process_messages
    self._consumer.commit_offsets()
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 750, in commit_offsets
    self._raise_worker_exceptions()
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 284, in _raise_worker_exceptions
    reraise(*self._worker_exception)
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 60, in wrapped
    ret = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 648, in _brokers_changed
    self._rebalance()
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 579, in _rebalance
    self.commit_offsets()
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 750, in commit_offsets
    self._raise_worker_exceptions()
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 284, in _raise_worker_exceptions
    reraise(*self._worker_exception)
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 60, in wrapped
    ret = fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 648, in _brokers_changed
    self._rebalance()
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 587, in _rebalance
    self._update_member_assignment()
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 556, in _update_member_assignment
    self._remove_partitions(current_zk_parts - new_partitions)
  File "/usr/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 607, in _remove_partitions
    self._zookeeper.delete(self._path_from_partition(p))
  File "/usr/local/lib/python2.7/site-packages/kazoo/client.py", line 1316, in delete
    return self.delete_async(path, version).get()
  File "/usr/local/lib/python2.7/site-packages/kazoo/handlers/utils.py", line 79, in get
    raise self._exception
NoNodeError
```

**Comment by emmett9001** [comment]
Thanks @rodrabe. As you can see from [these issues](https://github.com/Parsely/pykafka/issues?utf8=%E2%9C%93&q=is%3Aissue+nonodeerror+), particularly the discussion on #565, this error can be triggered in a bunch of different scenarios that involve brokers becoming inaccessible or specific relative timings in consumer group initialization.

Since you appear to be calling `commit_offsets` manually, you might consider catching the expected `NoNodeError` in your client code and restarting the consumer when it's encountered. This also points out a need for a clearer exception type, since it's known that this error can appear.
