### ISSUE TITLE
  use_rdkafka = True , and I have installed librdkafka

### ISSUE THREAD

**Issue by waytai** [Parsely/pykafka#778]
Traceback (most recent call last):                                                                          
  File "pyconsume.py", line 30, in <module>                                                                 
    use_rdkafka = True                                                                                      
  File "/usr/local/lib/python2.7/dist-packages/pykafka/topic.py", line 214, in get_balanced_consumer        
    return cls(self, self._cluster, consumer_group, **kwargs)                                               
  File "/usr/local/lib/python2.7/dist-packages/pykafka/managedbalancedconsumer.py", line 188, in __init__   
    self.__class__.__name__))                                                                               
ImportError: use_rdkafka is not available for ManagedBalancedConsumer                                       
Exception AttributeError: "'ManagedBalancedConsumer' object has no attribute '_running'" in <bound method Ma
nagedBalancedConsumer.__del__ of <pykafka.managedbalancedconsumer.ManagedBalancedConsumer at 0x7f5a65a31b10 
(consumer_group=KAFKA_01)>> ignored

**Comment by emmett9001** [comment]
At the time the `ManagedBalancedConsumer` was written, librdkafka didn't support Kafka-managed consumer groups, so this `ImportError` was added to make that clear. We should reexamine where librdkafka's support is these days, and fix this if possible. This will probably happen during Parse.ly's internal upgrade to latest Kafka later this year.

**Comment by waytai** [comment]
than you for your kindly reply
