### ISSUE TITLE
Can't delete topic using `pykafka/cli/kafka_tools.py` script

### ISSUE THREAD

**Issue by vikt0rs** [Parsely/pykafka#798]
Hello, folks,

I'm trying to remove a topic from Kafka using the `pykafka/cli/kafka_tools.py` script, but getting an error message `pykafka.exceptions.SocketDisconnectedError: <broker b'10.12.227.146':9092>`. Please, suggest, if I do something wrong.
You may find shell command and it's traceback below.

Thanks!

```
(py36) macmini987:notifications_api vserhei$ python .tox/py36/lib/python3.6/site-packages/pykafka/cli/kafka_tools.py --broker=10.12.227.146:9092 --broker_version=0.10.0 delete_topic test_topic_1
Traceback (most recent call last):
  File ".tox/py36/lib/python3.6/site-packages/pykafka/cli/kafka_tools.py", line 466, in <module>
    main()
  File ".tox/py36/lib/python3.6/site-packages/pykafka/cli/kafka_tools.py", line 460, in main
    args.func(client, args)
  File ".tox/py36/lib/python3.6/site-packages/pykafka/cli/kafka_tools.py", line 280, in delete_topic
    client.cluster.controller_broker.delete_topics([args.topic], args.timeout)
  File "/Users/vserhei/src/notifications_api/.tox/py36/lib/python3.6/site-packages/pykafka/broker.py", line 45, in wrapped
    return fn(self, *args, **kwargs)
  File "/Users/vserhei/src/notifications_api/.tox/py36/lib/python3.6/site-packages/pykafka/broker.py", line 584, in delete_topics
    return future.get(DeleteTopicsResponse)
  File "/Users/vserhei/src/notifications_api/.tox/py36/lib/python3.6/site-packages/pykafka/handlers.py", line 74, in get
    raise self.error
  File "/Users/vserhei/src/notifications_api/.tox/py36/lib/python3.6/site-packages/pykafka/handlers.py", line 212, in worker
    res = shared.connection.response()
  File "/Users/vserhei/src/notifications_api/.tox/py36/lib/python3.6/site-packages/pykafka/connection.py", line 217, in response
    raise SocketDisconnectedError("<broker {}:{}>".format(self.host, self.port))
pykafka.exceptions.SocketDisconnectedError: <broker b'10.12.227.146':9092>
(py36) macmini987:notifications_api vserhei$
(py36) macmini987:notifications_api vserhei$
(py36) macmini987:notifications_api vserhei$ pip freeze | grep pykafka
pykafka==2.7.0
(py36) macmini987:notifications_api vserhei$
```

**Comment by emmett9001** [comment]
Hi @vikt0rs, and thanks for your report. I see that you've set `--broker-version` to `0.10.0`, but what version of Kafka are the brokers you're talking to actually running? A mismatch there is a likely cause of this error.

**Comment by vikt0rs** [comment]
Hello, @emmett9001. 

Yes, it is `0.10.0` (at least, I think so based on the server `ps` command). If you suggest a trusty way to check it, I'll do it and inform you about the result.

Thanks!

**Comment by emmett9001** [comment]
Oops, looks like topic creation/deletion APIs were [added](https://issues.apache.org/jira/browse/KAFKA-2946) in 0.10.1, not 0.10.0. I'll fix that check in the `Broker` code.

**Comment by emmett9001** [comment]
Fixed here https://github.com/Parsely/pykafka/commit/7cf21a68b2a8848c632001a88e7ede0d959eea8b
