### ISSUE TITLE
gevent upgrade breaks pykafka 2.4.0 import

### ISSUE THREAD

**Issue by eedwards-sk** [Parsely/pykafka#801]
**PyKafka version**: `pykafka==2.4.0`
**Kafka version**: N\A

pykafka `2.4.0` is failing to import due to revision on `gevent` library

previous working version of gevent which was getting installed was `1.2.2`, but now it's pulling in version `1.3.0` which breaks as below:

```
  File "/home/ubuntu/our-product/libs/pos/task/common.py", line 11, in <module>

    from core.kafka.kafka_utils import send_kafka

  File "/home/ubuntu/our-product/core/kafka/kafka_utils.py", line 6, in <module>

    from pykafka import KafkaClient

  File "/home/ubuntu/our-product/.tox/py27/local/lib/python2.7/site-packages/pykafka/__init__.py", line 3, in <module>

    from .cluster import Cluster

  File "/home/ubuntu/our-product/.tox/py27/local/lib/python2.7/site-packages/pykafka/cluster.py", line 36, in <module>

    from .topic import Topic

  File "/home/ubuntu/our-product/.tox/py27/local/lib/python2.7/site-packages/pykafka/topic.py", line 23, in <module>

    from .balancedconsumer import BalancedConsumer

  File "/home/ubuntu/our-product/.tox/py27/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 31, in <module>

    from kazoo.handlers.gevent import SequentialGeventHandler

  File "/home/ubuntu/our-product/.tox/py27/local/lib/python2.7/site-packages/kazoo/handlers/gevent.py", line 32, in <module>

    class SequentialGeventHandler(object):

  File "/home/ubuntu/our-product/.tox/py27/local/lib/python2.7/site-packages/kazoo/handlers/gevent.py", line 63, in SequentialGeventHandler

    class timeout_exception(gevent.event.Timeout):

AttributeError: 'module' object has no attribute 'Timeout'
```

We're on a fairly older version of pykafka, so I'm hoping there's a slightly newer version that might have changed the requirement that we can easily upgrade to, otherwise we're just pinning `gevent==1.2.2` for now.

A patch revision on 2.4.0 that pessimistically pins to `gevent ~>1.2` would also work.

Thanks

**Comment by DavidEllis008** [comment]
PyKafka version: pykafka==2.5.0

We are seeing the same problem with Gevent's latest release.

```
Traceback (most recent call last):
  File "/test/test_collect.py", line 14, in <module>
    from collectlib.collect import collect_main
  File "/app/collectlib/collect.py", line 25, in <module>
    from pykafka import KafkaClient
  File "/usr/local/lib/python2.7/dist-packages/pykafka/__init__.py", line 3, in <module>
    from .cluster import Cluster
  File "/usr/local/lib/python2.7/dist-packages/pykafka/cluster.py", line 36, in <module>
    from .topic import Topic
  File "/usr/local/lib/python2.7/dist-packages/pykafka/topic.py", line 23, in <module>
    from .balancedconsumer import BalancedConsumer
  File "/usr/local/lib/python2.7/dist-packages/pykafka/balancedconsumer.py", line 31, in <module>
    from kazoo.handlers.gevent import SequentialGeventHandler
  File "/usr/local/lib/python2.7/dist-packages/kazoo/handlers/gevent.py", line 32, in <module>
    class SequentialGeventHandler(object):
  File "/usr/local/lib/python2.7/dist-packages/kazoo/handlers/gevent.py", line 63, in SequentialGeventHandler
    class timeout_exception(gevent.event.Timeout):
AttributeError: 'module' object has no attribute 'Timeout'
```
It looks like GEVENT has ballooned from 1.6 MB to 4.2MB

Our (old) successful build using
```
Collecting gevent>=1.1.0 (from pykafka==2.5.0->-r /workspace/requirements.txt (line 3))
Downloading gevent-1.2.2-cp27-cp27mu-manylinux1_x86_64.whl (1.6MB)
```

And the new one that is crashing with the above error:

```
Collecting gevent>=1.1.0 (from pykafka==2.5.0->-r /workspace/requirements.txt (line 3))
Downloading https://files.pythonhosted.org/packages/4f/12/8d06eafbddf8e58cfd3869319e087d9f5d2eb052e0374b87f6b153042b1c/gevent-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl (4.2MB)

```

We have taken to pinning the version of GEVENT to `gevent==1.2.2` . This fixes our issue for now.

**Comment by emmett9001** [comment]
@eedwards-sk @DavidEllis008 thanks for the reports. Apparently this is due to Kazoo's reliance on a non-public gevent API, which has been fixed in its master branch. For the time until that change is released in a numbered version, I've pinned pykafka's gevent dependency [here](https://github.com/Parsely/pykafka/pull/803).

**Comment by carsonip** [comment]
Just a side note: I have submitted a PR to kazoo last month and it has been merged. But it appears that they are not releasing a new version yet. https://github.com/python-zk/kazoo/pull/503

**Comment by carsonip** [comment]
@emmett9001 A new kazoo release is ready. Can we use gevent 1.3 now? Thanks.
https://github.com/python-zk/kazoo/commit/66fa0dfbe1234ad0431f142c5c9c3381d88828cd

**Comment by emmett9001** [comment]
@carsonip pull requested here https://github.com/Parsely/pykafka/pull/818
