### ISSUE TITLE
samsa bug

### ISSUE THREAD

**Issue by cysy-lil** [Parsely/pykafka#822]
when I  write a demo which from https://pypi.org/project/samsa/, then I run it, but throw a error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\Python27\lib\site-packages\samsa\cluster.py", line 44,
in __init__
    self.brokers = BrokerMap(self)
  File "D:\Program Files\Python27\lib\site-packages\samsa\brokers.py", line 45,
in __init__
    self._node_path, self._configure
  File "D:\Program Files\Python27\lib\site-packages\kazoo\recipe\watchers.py", l
ine 290, in __init__
    self._get_children()
  File "D:\Program Files\Python27\lib\site-packages\kazoo\recipe\watchers.py", l
ine 37, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\Python27\lib\site-packages\kazoo\recipe\watchers.py", l
ine 340, in _get_children
    result = self._func(children)
  File "D:\Program Files\Python27\lib\site-packages\samsa\brokers.py", line 66,
in _configure
    broker = Broker(self.cluster, id_=broker_id)
  File "D:\Program Files\Python27\lib\site-packages\samsa\brokers.py", line 146,
 in __init__
    self._node_path, self._configure
  File "D:\Program Files\Python27\lib\site-packages\kazoo\recipe\watchers.py", l
ine 131, in __init__
    self._get_data()
  File "D:\Program Files\Python27\lib\site-packages\kazoo\recipe\watchers.py", l
ine 37, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\Python27\lib\site-packages\kazoo\recipe\watchers.py", l
ine 206, in _get_data
    self._log_func_exception(data, stat, event)
  File "D:\Program Files\Python27\lib\site-packages\kazoo\recipe\watchers.py", l
ine 164, in _log_func_exception
    result = self._func(data, stat)
  File "D:\Program Files\Python27\lib\site-packages\samsa\brokers.py", line 160,
 in _configure
    creator, self.__host, port = data.split(':')
ValueError: too many values to unpack
```
then I edit the source of samsa brokers.py:
```python
    def _configure(self, data, stat):
        """
        Configures a broker based on it's state in ZooKeeper.
        """
        logger.info('Retrieved broker data for %s...', self)
        if data is None:
            logger.info('Broker data field was empty. Assuming it was dead.')
            self.__host = self.__port = None
        else:
            jsonObj = json.loads(data)
            print jsonObj
            print jsonObj['host']
            # creator, self.__host, port = data.split(':')
            self.__host=jsonObj['host']
            self.__port=jsonObj['port']
            # self.__port = int(port)
```
then I run it again,but throw a new error:
```
No handlers could be found for logger "kazoo.recipe.watchers"
Traceback (most recent call last):
  File "D:/workspace/pyCharm/nlp/extractKey/kafka_test1.py", line 7, in <module>
    topic = cluster.topics['zaful']
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\samsa\topics.py", line 50, in __getitem__
    return self.get(key)
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\samsa\topics.py", line 59, in get
    topic = self.__topics[name] = Topic(self.cluster, name)
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\samsa\topics.py", line 79, in __init__
    self.partitions = PartitionMap(self.cluster, self)
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\samsa\partitions.py", line 53, in __init__
    self._topic_changed, allow_missing_node=True
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\kazoo\recipe\watchers.py", line 131, in __init__
    self._get_data()
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\kazoo\recipe\watchers.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\kazoo\recipe\watchers.py", line 206, in _get_data
    self._log_func_exception(data, stat, event)
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\kazoo\recipe\watchers.py", line 164, in _log_func_exception
    result = self._func(data, stat)
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\samsa\partitions.py", line 62, in _topic_changed
    self._configure
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\kazoo\recipe\watchers.py", line 290, in __init__
    self._get_children()
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\kazoo\recipe\watchers.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\kazoo\recipe\watchers.py", line 340, in _get_children
    result = self._func(children)
  File "D:\workspace\pyCharm\nlp\extractKey\venv\lib\site-packages\samsa\partitions.py", line 69, in _configure
    brokers = map(self.cluster.brokers.get, map(int, broker_ids))
ValueError: invalid literal for int() with base 10: 'partitions'
```

**Comment by emmett9001** [comment]
@cysy-lil Unfortunately you're using a version of this library that is no longer supported. I recommend using `pykafka==2.7.0` instead of `samsa`. They have similar interfaces, and we'll be able to provide support for more recent pykafka versions. You can get the latest version with `pip install pykafka`.
