### ISSUE TITLE
Balanced_consumer keeps timing out and exiting

### ISSUE THREAD

**Issue by MokhFn** [Parsely/pykafka#826]
I am using a pykafka 2.5.0 (and 2.8.0-dev.2 just to make sure this is not version-related, at least starting from 2.5) to consume messages from a kafka cluster.

On a development machine, it all works fine, but on the production environment, where i am trying to migrate, my consumer doesn't seem to connect to the zookeeper. I tried to start a simple consumer, and it works fine. The zookeeper servers are pingable and reachable.

This is my log output (starting from the balanced consumer instanciation) : 

`2018-07-05 13:03:50,891 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
INFO:pykafka.handlers:RequestHandler worker: exiting cleanly
2018-07-05 13:03:51,212 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
INFO:pykafka.handlers:RequestHandler worker: exiting cleanly
WARNING:kazoo.client:Connection dropped: socket connection error: None
2018-07-05 13:04:50,295 - pykafka.balancedconsumer - ERROR - Stopping consumer in response to error
Traceback (most recent call last):
  File "/opt/consumer/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 332, in start
    self._zookeeper_connection_timeout_ms)
  File "/opt/consumer/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 382, in _setup_zookeeper
    self._zookeeper.start()
  File "/opt/consumer/lib/python2.7/site-packages/kazoo/client.py", line 560, in start
    raise self.handler.timeout_exception("Connection time-out")
KazooTimeoutError: Connection time-out
ERROR:pykafka.balancedconsumer:Stopping consumer in response to error
Traceback (most recent call last):
  File "/opt/consumer/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 332, in start
    self._zookeeper_connection_timeout_ms)
  File "/opt/consumer/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 382, in _setup_zookeeper
    self._zookeeper.start()
  File "/opt/consumer/lib/python2.7/site-packages/kazoo/client.py", line 560, in start
    raise self.handler.timeout_exception("Connection time-out")
KazooTimeoutError: Connection time-out
2018-07-05 13:04:50,296 - pykafka.balancedconsumer - DEBUG - Stopping <pykafka.balancedconsumer.BalancedConsumer at 0x7f14c6b8bd90 (consumer_group=consumer_radio_data)>
DEBUG:pykafka.balancedconsumer:Stopping <pykafka.balancedconsumer.BalancedConsumer at 0x7f14c6b8bd90 (consumer_group=consumer_radio_data)>
Traceback (most recent call last):
  File "scripts/pykafka_consumer.py", line 78, in <module>
    # Rework following if, pre-prepare it
  File "/opt/consumer/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 766, in __iter__
    message = self.consume(block=True)
  File "/opt/consumer/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 756, in consume
    raise ConsumerStoppedException
pykafka.exceptions.ConsumerStoppedException
2018-07-05 13:04:50,324 - pykafka.balancedconsumer - DEBUG - Finalising <pykafka.balancedconsumer.BalancedConsumer at 0x7f14c6b8bd90 (consumer_group=consumer_radio_data)>
DEBUG:pykafka.balancedconsumer:Finalising <pykafka.balancedconsumer.BalancedConsumer at 0x7f14c6b8bd90 (consumer_group=consumer_radio_data)>
2018-07-05 13:04:50,325 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
2018-07-05 13:04:50,325 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
2018-07-05 13:04:50,325 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
2018-07-05 13:04:50,325 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
`

**Comment by emmett9001** [comment]
Thanks for the issue report. How are you providing the ZooKeeper host string to pykafka? The standard way to do this is with `zookeeper_hosts` [here](http://pykafka.readthedocs.io/en/latest/api/client.html#pykafka.client.KafkaClient).

**Comment by MokhFn** [comment]
I am calling it like this : 
`consumer = topic.get_balanced_consumer(
    consumer_group='consumer_radio_data',
    auto_commit_enable=False,
    zookeeper_connect='zookeeper01.address:2181,zookeeper02.address:2181,zookeeper03.address:2181',
    auto_offset_reset=OffsetType.LATEST,
    reset_offset_on_start=True,
)`

If needed, i could post more code chunks, or the whole thing :)

**Comment by emmett9001** [comment]
What happens when you run this from the same server you're trying to make a `BalancedConsumer` on?
```python
from kazoo.client import KazooClient
zk = KazooClient('zookeeper01.address:2181,zookeeper02.address:2181,zookeeper03.address:2181')
zk.start()
```

**Comment by MokhFn** [comment]
Outputs the following : 
`No handlers could be found for logger "kazoo.client"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/openei/lib/python2.7/site-packages/kazoo/client.py", line 560, in start
    raise self.handler.timeout_exception("Connection time-out")
kazoo.handlers.threading.KazooTimeoutError: Connection time-out
`

And on my dev machine, it works like a charm, outputs nothing and runs properly.

**Comment by emmett9001** [comment]
That error indicates that the machine you're attempting to run on is unable to connect to the ZooKeeper cluster you're pointing pykafka to. Once that's resolved, you should find that pykafka can run just fine.

**Comment by MokhFn** [comment]
How is it unreachable if it is pingable and traceroute'able ?

**Comment by emmett9001** [comment]
It's possible that the particular port `2181` on which you're trying to connect to the zookeeper nodes is not accessible.

**Comment by MokhFn** [comment]
Might be, but why is it accessible from another machine  and not this one, particularly ?

**Comment by emmett9001** [comment]
The answer to that depends on the particular configuration of the two machines in question as well as any firewalls or other network configurations you might have set up that could be limiting traffic between the two machines.
