### ISSUE TITLE
KeyError: 17 when auto-creating an illegal topic name

### ISSUE THREAD

**Issue by Richard-Foo** [Parsely/pykafka#846]
Connecting to (auto-creating) a non-existent topic with a name that violates rules (e.g., '/sys/foo') causes a fatal error in PyKafka's error reporting.

$ ./test.py 
Topic b'/sys/foo' not found. Attempting to auto-create.
Traceback (most recent call last):
  File "./test.py", line 15, in <module>
    **topic = client.topics[b'/sys/foo']**
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pykafka/cluster.py", line 63, in __getitem__
    topic_ref = super(TopicDict, self).__getitem__(key)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pykafka/cluster.py", line 82, in __missing__
    self._create_topic(key)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pykafka/cluster.py", line 111, in _create_topic
    **raise ERROR_CODES[err](
KeyError: 17**

$ pip3 show pykafka
Name: pykafka
Version: 2.7.0

**Comment by emmett9001** [comment]
Thanks @Richard-Foo. This exception needs to be added to the set of supported exception classes.
