### ISSUE TITLE
ImportError: cannot import name '_rd_kafka'

### ISSUE THREAD

**Issue by sunhailin-Leo** [Parsely/pykafka#850]
**PyKafka version**: 2.7.0
**Kafka version**: 1.0.0
**Python version**: 3.5.4

```Python
Traceback (most recent call last):
  File "C:\Python\Python35\lib\site-packages\pykafka\topic.py", line 42, in <module>
    from . import rdkafka
  File "C:\Python\Python35\lib\site-packages\pykafka\rdkafka\__init__.py", line 1, in <module>
    from .producer import RdKafkaProducer
  File "C:\Python\Python35\lib\site-packages\pykafka\rdkafka\producer.py", line 7, in <module>
    from . import _rd_kafka
ImportError: cannot import name '_rd_kafka'
```

This error happened when I run in a multiprocess mode.

**Comment by emmett9001** [comment]
Thanks @sunhailin-Leo. How did you install pykafka? The `setup.py` file [attempts](https://github.com/Parsely/pykafka/blob/d8ed3dc7ae8877be5a6f0081e93223632cd5df7f/setup.py#L127) to install the C extension for rdkafka compatibility.

**Comment by sunhailin-Leo** [comment]
I use ```pip install pykafka``` install the pykafka.
em... I tried to install it in another way. :smile:

**Comment by emmett9001** [comment]
You need to have `librdkafka` on your system library path before running `pip install pykafka` if you want the installation to build the rdkafka extension. Uninstall pykafka, install `librdkafka`, then try re-running `pip install pykafka`.

**Comment by DanielFallon** [comment]
@sunhailin-Leo  run `pip install --ignore-installed -v pykafka`

with librdkafka 0.11.4 and later, I've found that the rdkafka build is broken, I get a message like this:

```
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.7
m -c pykafka/rdkafka/_rd_kafkamodule.c -o build/temp.linux-x86_64-3.7/pykafka/rdkafka/_rd_kafkamodule.o
  pykafka/rdkafka/_rd_kafkamodule.c: In function 'RdkHandle_start':
  pykafka/rdkafka/_rd_kafkamodule.c:492:9: warning: 'rd_kafka_errno2err' is deprecated [-Wdeprecated-declarations]
           set_pykafka_error_from_code(rd_kafka_errno2err(errno), NULL);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from pykafka/rdkafka/_rd_kafkamodule.c:11:0:
  /usr/include/librdkafka/rdkafka.h:570:21: note: declared here
   rd_kafka_resp_err_t rd_kafka_errno2err(int errnox);
                       ^~~~~~~~~~~~~~~~~~
  pykafka/rdkafka/_rd_kafkamodule.c: In function 'Producer_produce':
  pykafka/rdkafka/_rd_kafkamodule.c:682:9: warning: 'rd_kafka_errno2err' is deprecated [-Wdeprecated-declarations]
           rd_kafka_resp_err_t err = rd_kafka_errno2err(errno);
           ^~~~~~~~~~~~~~~~~~~
  In file included from pykafka/rdkafka/_rd_kafkamodule.c:11:0:
  /usr/include/librdkafka/rdkafka.h:570:21: note: declared here
   rd_kafka_resp_err_t rd_kafka_errno2err(int errnox);
                       ^~~~~~~~~~~~~~~~~~
  pykafka/rdkafka/_rd_kafkamodule.c: In function 'Consumer_stop':
  pykafka/rdkafka/_rd_kafkamodule.c:803:17: warning: 'rd_kafka_errno2err' is deprecated [-Wdeprecated-declarations]
                   set_pykafka_error_from_code(rd_kafka_errno2err(errno), NULL);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from pykafka/rdkafka/_rd_kafkamodule.c:11:0:
  /usr/include/librdkafka/rdkafka.h:570:21: note: declared here
   rd_kafka_resp_err_t rd_kafka_errno2err(int errnox);
                       ^~~~~~~~~~~~~~~~~~
  pykafka/rdkafka/_rd_kafkamodule.c: In function 'Consumer_start':
  pykafka/rdkafka/_rd_kafkamodule.c:935:13: warning: 'rd_kafka_errno2err' is deprecated [-Wdeprecated-declarations]
               set_pykafka_error_from_code(rd_kafka_errno2err(errno), NULL);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from pykafka/rdkafka/_rd_kafkamodule.c:11:0:
  /usr/include/librdkafka/rdkafka.h:570:21: note: declared here
   rd_kafka_resp_err_t rd_kafka_errno2err(int errnox);
                       ^~~~~~~~~~~~~~~~~~
  gcc -shared build/temp.linux-x86_64-3.7/pykafka/rdkafka/_rd_kafkamodule.o -L/usr/local/lib -lrdkafka -lpython3.7m -o build/lib.linux-x86_64-3.7/pykafka/rdkafka/_rd_kafka.cpython-37m-x86_64-linux-gnu.so
```

**Comment by sumeetsarkar** [comment]
I faced this problem recently. I was getting the below error:

`raise ImportError("use_rdkafka requires rdkafka to be installed")`

My setup when I was facing the problem was:

_(The order below is important for this to work, what I believed and ideally it should work, for me it did not)_

```
brew install librdkafka
pip install pykafka
```

**Note:** Even using LD_LIBRARY_PATH with correct path for librdkafka lib it did not work.

**Solution**

```
# Uninstall pykafka if installed in your env
pip uninstall pykafka

# Clone pykafka in your project
git clone git@github.com:Parsely/pykafka.git && cd pykafka

# Build rdkafka
python setup.py develop

# Test if rdkafka is available
python -c "from pykafka import rdkafka"
```

If all steps above are followed well, `from pykafka import rdkafka` works without any errors

**Comment by carsonip** [comment]
Please see #926 if you have issues with setting up pykafka + rdkafka. Also, when #920 is fixed, it would be easier to install (and debug if it fails) pykafka with rdkafka setup. I suppose this issue can be closed for now. @emmett9001
