### ISSUE TITLE
logging when log doesn't exists :bug in old release

### ISSUE THREAD

**Issue by vijuSR** [Parsely/pykafka#863]
Noticed the following exception:

`Exception ignored in: <bound method RequestHandler.__del__ of <pykafka.handlers.RequestHandler object at 0x00000050FD225
828>>
Traceback (most recent call last):
  File "G:\VENVIRONMENT\granular\lib\site-packages\pykafka\handlers.py", line 164, in __del__
  File "G:\VENVIRONMENT\granular\lib\site-packages\pykafka\handlers.py", line 189, in stop
  File "C:\Python36\lib\logging\__init__.py", line 1306, in info
  File "C:\Python36\lib\logging\__init__.py", line 1442, in _log
  File "C:\Python36\lib\logging\__init__.py", line 1452, in handle
  File "C:\Python36\lib\logging\__init__.py", line 1514, in callHandlers
  File "C:\Python36\lib\logging\__init__.py", line 863, in handle
  File "C:\Python36\lib\logging\__init__.py", line 1069, in emit
  File "C:\Python36\lib\logging\__init__.py", line 1059, in _open
NameError: name 'open' is not defined`

After checking the [code](https://github.com/Parsely/pykafka/blob/286b33da301e714e5a97b268936aee35a2c5c662/pykafka/handlers.py#L189) found it has been already resolved. So when to expect the new release.

**Comment by emmett9001** [comment]
There are enough changes since 2.7.0 for a new minor version release. It needs to be tested for a bit, so I wouldn't expect it for the next month at least. In the meantime you can depend on `2.8.0-dev.3` if you need this change.

**Comment by sunhailin-Leo** [comment]
This error has been solved yet？
I use 2.8.0-dev.5 、2.8.1-dev.1 also have this problem.

**Comment by emmett9001** [comment]
@sunhailin-Leo When does this error happen? It looks like something that would happen during interpreter shutdown. Maybe you can provide some code that reproduces the issue?
