### ISSUE TITLE
Kafka consumer runtime throws an exception

### ISSUE THREAD

**Issue by zengzhiying** [Parsely/pykafka#893]
One of my online programs, the runtime throws the following error. 

```
Traceback (most recent call last):
  File "bulk_srvdb_scylla.py", line 334, in <module>
    message = balanced_consumer.consume()
  File "/yisa_bigdata/python2.7/lib/python2.7/site-packages/pykafka-2.8.0-py2.7-linux-x86_64.egg/pykafka/balancedconsumer.py", line 748, in consume
    message = self._consumer.consume(block=block, unblock_event=self._rebalancing_in_progress)
  File "/yisa_bigdata/python2.7/lib/python2.7/site-packages/pykafka-2.8.0-py2.7-linux-x86_64.egg/pykafka/simpleconsumer.py", line 483, in consume
    self._raise_worker_exceptions()
  File "/yisa_bigdata/python2.7/lib/python2.7/site-packages/pykafka-2.8.0-py2.7-linux-x86_64.egg/pykafka/simpleconsumer.py", line 276, in _raise_worker_exceptions
    reraise(*self._worker_exception)
  File "/yisa_bigdata/python2.7/lib/python2.7/site-packages/pykafka-2.8.0-py2.7-linux-x86_64.egg/pykafka/simpleconsumer.py", line 440, in fetcher
    self.fetch()
  File "/yisa_bigdata/python2.7/lib/python2.7/site-packages/pykafka-2.8.0-py2.7-linux-x86_64.egg/pykafka/simpleconsumer.py", line 823, in fetch
    success_handler=_handle_success)
  File "/yisa_bigdata/python2.7/lib/python2.7/site-packages/pykafka-2.8.0-py2.7-linux-x86_64.egg/pykafka/utils/error_handlers.py", line 50, in handle_partition_responses
    error_handlers[errcode](parts)
KeyError: 2
```
The consumer structure in the code is as follows: 
```python
 kafka_client = KafkaClient(zookeeper_hosts=configs['kafka']['zookeeper_hosts'])
 topic = kafka_client.topics[configs['kafka']['topic']]
 balanced_consumer = topic.get_balanced_consumer(
        consumer_group=configs['kafka']['group_id'],
        auto_commit_enable=True,
        reset_offset_on_start=False,
        auto_offset_reset=OffsetType.LATEST,
        zookeeper_connect=configs['kafka']['zookeeper_hosts']
 )
```
The program has been running stably before, and the parameters have not been modified during the operation.
What is the reason? thank you very much

Kafka Version: kafka_2.11-1.0.1
pykafka Version: 2.8.0
python Version: 2.7.5

Excuse me, my English is poor.

**Comment by emmett9001** [comment]
Looks like this is an oversight in the default error handlers in the `SimpleConsumer`. [This error](https://github.com/Parsely/pykafka/blob/1fb7642d9e82dba3a6332be4f7d5d211ae1e50d7/pykafka/exceptions.py#L121) needs to be included [here](https://github.com/Parsely/pykafka/blob/1fb7642d9e82dba3a6332be4f7d5d211ae1e50d7/pykafka/simpleconsumer.py#L348).

**Comment by zengzhiying** [comment]
@emmett9001 I understand, thank you very much.
