### ISSUE TITLE
pykafka.exceptions.UnknownTopicOrPartition after kafka topic partition reassignment

### ISSUE THREAD

**Issue by ethicalmohit** [Parsely/pykafka#909]
We are using sync pykafka producer with 3 nodes of the kafka cluster. We were trying to replace a broker in the cluster in order to do some upgrades.

We have done partition reassignment manually of that particular topic to other 2 Kafka brokers while Kafka producer was already running. The partition reassignment was successful but we got the below error as it was trying to communicate with the broker which is no longer serving as a producer for that topic/partition.

This goes on until the application server is restarted, i.e; the KafkaClient object is re-created.

```
def send(self, topic_name: str, data, raise_exception=False) -> None:
        """Publishes a message on a topic
        """
        message = self.encode(data)
        topic = self.client.topics[topic_name.encode('utf-8')]
        try:
            with topic.get_sync_producer(linger_ms=0) as producer:
                producer.produce(message)
        except Exception as e:
            monitoring.record_exception()
            logger.exception('Pushing entry to kafka failed for topic: {topic} and message: {message}'.format(
                topic=topic.name,
                message=message
            ))
            if raise_exception:
                raise e
```
Actual Behaviour:

```
[WARNING] [2018-12-20 11:13:33,482] [pykafka.producer] [producer.py:520] Produce request for b'test-load-2001'/2 to b'172.16.45.154':9092 failed with error code 3.
[WARNING] [2018-12-20 11:13:33,607] [pykafka.producer] [producer.py:520] Produce request for b'test-load-2001'/2 to b'172.16.45.154':9092 failed with error code 3.
[WARNING] [2018-12-20 11:13:33,778] [pykafka.producer] [producer.py:520] Produce request for b'test-load-2001'/2 to b'172.16.45.154':9092 failed with error code 3.
[WARNING] [2018-12-20 11:13:33,907] [pykafka.producer] [producer.py:520] Produce request for b'test-load-2001'/2 to b'172.16.45.154':9092 failed with error code 3.
[ERROR] [2018-12-20 11:13:34,092] [pykafka.producer] [producer.py:551] Message not delivered!! UnknownTopicOrPartition("Produce request for b'test-load-2001'/2 to b'172.16.45.154':9092 failed with error code 3.",)
[ERROR] [2018-12-20 11:13:34,095] [root] [<console>:8] Failure.
Traceback (most recent call last):
  File "<console>", line 5, in <module>
  File "/usr/local/lib/python3.6/site-packages/pykafka/producer.py", line 413, in produce
    raise exc
pykafka.exceptions.UnknownTopicOrPartition: Produce request for b'test-load-2001'/2 to b'172.16.45.154':9092 failed with error code 3.
```

Expected behavior: Kafka client should recover from these errors automatically, by updating cluster metadata.

**PyKafka version**:  3.6
**Kafka version**: 1.1.0

**Comment by emmett9001** [comment]
Thank you for the report, @ethicalmohit. I have a hunch that this error could be handled by adding a check for `UnknownTopicOrPartition` to [this conditional](https://github.com/Parsely/pykafka/blob/b8f0268a6a3aeabebdd4d5a80a3ec58506241469/pykafka/producer.py#L511).

**Comment by ethicalmohit** [comment]
> Please try out #911 and see if it fixes your issue.

Thanks for the quick solution. We are unable to reproduce the error now.
