### ISSUE TITLE
Loosing messages when producing

### ISSUE THREAD

**Issue by rubinatorz** [Parsely/pykafka#912]
Hi @emmett9001 ,

We have a problematic thing going on with producing messages. We have an application running with a number of consumers and two producers. Consuming occurs continuously, but producing is just every 30 minutes (due to batch processing of input file). When starting the application and running the first batch, everything works fine. Which means every message that is produced, is available on the topic and can be consumed by the consuming application. But after 30 minutes when the 2nd batch is processed, we are getting "Error encountered when producing to broker x. Retrying." errors in the debuglog of pykafka and we are loosing some messages. With other words we send for example 100 messages, but always a few are gone (1 or 2). So they never arrive on the topic and are thus not consumed by the consuming application. This happens on both producers, each producing to a separate topic. We are running the producer in asynchronous mode (sync=False on get_producer).

When running in synchronous mode (sync=True), same error appears in the debuglog, but none of the messages are gone. So 100% of the messages produced appear on the topic.

We are running pykafka 2.8.0, but also tried 2.7.0. We have a Kafka cluster setup of 3 nodes, with replication-factor 3 for all the topics. Kafka version is 1.1.0.

Underneath is a part of the debuglog of pykafka where you can see the errors I mentioned.

Looking at the pykafka code, I think the "Error encountered when producing to broker x. Retrying." errors is because of a SocketDisconnectedError. I guess that in the 30 minutes between producing, the connection is lost somehow due to timeouts. It successfully reconnects in both sync and async mode, but unfortunately messages are lost in async mode.

Any thoughts on this? 

Thank you very much.

----
2019-01-25 12:11:00,622 Sending 1 messages to broker 2
2019-01-25 12:11:00,622 Sending 1 messages to broker 0
2019-01-25 12:11:00,632 Error encountered when producing to broker ip:9092. Retrying.
2019-01-25 12:11:00,633 Updating cluster, attempt 1/3
2019-01-25 12:11:00,634 Error encountered when producing to broker ip:9292. Retrying.
2019-01-25 12:11:00,634 Updating cluster, attempt 1/3
2019-01-25 12:11:00,635 Connecting to ip:9092
2019-01-25 12:11:00,635 Connecting to ip:9092
2019-01-25 12:11:00,636 Successfully connected to ip:9092
2019-01-25 12:11:00,636 Successfully connected to ip:9092
2019-01-25 12:11:00,640 RequestHandler.stop: about to flush requests queue
2019-01-25 12:11:00,641 Discovered 3 brokers
2019-01-25 12:11:00,641 Reconnecting to broker id 0: ip:9092
2019-01-25 12:11:00,643 Connecting to ip:9092
2019-01-25 12:11:00,644 Successfully connected to ip:9092
2019-01-25 12:11:00,644 RequestHandler.stop: about to flush requests queue
2019-01-25 12:11:00,645 RequestHandler.stop: about to flush requests queue
2019-01-25 12:11:00,647 Discovered 3 brokers
2019-01-25 12:11:00,647 Broker ip:9092 metadata unchanged. Continuing.
2019-01-25 12:11:00,647 Broker ip:9192 metadata unchanged. Continuing.
2019-01-25 12:11:00,648 Reconnecting to broker id 2: ip:9292
2019-01-25 12:11:00,649 Connecting to ip:9292
2019-01-25 12:11:00,649 Broker ip:9192 metadata unchanged. Continuing.
2019-01-25 12:11:00,649 Broker ip:9292 metadata unchanged. Continuing.
2019-01-25 12:11:00,650 Discovered 16 topics
2019-01-25 12:11:00,650 Adding 1 partitions
2019-01-25 12:11:00,650 Starting new produce worker for broker 0
2019-01-25 12:11:00,650 Successfully connected to ip:9292
2019-01-25 12:11:00,650 RequestHandler.stop: about to flush requests queue
2019-01-25 12:11:00,652 Discovered 16 topics
2019-01-25 12:11:00,652 Adding 1 partitions
2019-01-25 12:11:00,652 Starting new produce worker for broker 2
2019-01-25 12:11:00,656 Successfully sent 0/1 messages to broker 0
2019-01-25 12:11:00,656 Successfully sent 0/1 messages to broker 2
2019-01-25 12:11:00,663 Sending 1 messages to broker 0
2019-01-25 12:11:00,663 Sending 1 messages to broker 2
2019-01-25 12:11:00,668 Fetched 1 messages for partition 0
2019-01-25 12:11:00,668 Partition 0 queue holds 1 messages
2019-01-25 12:11:00,669 Successfully sent 1/1 messages to broker 2
2019-01-25 12:11:00,672 Successfully sent 1/1 messages to broker 0
2019-01-25 12:11:00,675 Fetched 1 messages for partition 0
2019-01-25 12:11:00,675 Partition 0 queue holds 1 messages
2019-01-25 12:11:00,680 Sending 1 messages to broker 2
2019-01-25 12:11:00,681 Sending 1 messages to broker 0
2019-01-25 12:11:00,687 Successfully sent 1/1 messages to broker 2
2019-01-25 12:11:00,687 Fetched 1 messages for partition 0
2019-01-25 12:11:00,687 Partition 0 queue holds 1 messages
2019-01-25 12:11:00,688 Successfully sent 1/1 messages to broker 0
2019-01-25 12:11:00,692 Sending 1 messages to broker 0
2019-01-25 12:11:00,692 Sending 1 messages to broker 2
2019-01-25 12:11:00,693 Sending 1 messages to broker 2
2019-01-25 12:11:00,694 Fetched 1 messages for partition 0
2019-01-25 12:11:00,695 Partition 0 queue holds 1 messages
2019-01-25 12:11:00,697 Successfully sent 1/1 messages to broker 2
2019-01-25 12:11:00,697 Successfully sent 1/1 messages to broker 0
2019-01-25 12:11:00,698 Sending 1 messages to broker 2
2019-01-25 12:11:00,698 Sending 1 messages to broker 0
2019-01-25 12:11:00,701 Successfully sent 1/1 messages to broker 2
2019-01-25 12:11:00,702 Successfully sent 1/1 messages to broker 0
2019-01-25 12:11:00,704 Fetched 2 messages for partition 0
2019-01-25 12:11:00,704 Partition 0 queue holds 2 messages
2019-01-25 12:11:00,705 Sending 1 messages to broker 2
2019-01-25 12:11:00,706 Sending 1 messages to broker 0
2019-01-25 12:11:00,710 Successfully sent 1/1 messages to broker 2
2019-01-25 12:11:00,710 Sending 1 messages to broker 2
2019-01-25 12:11:00,711 Successfully sent 1/1 messages to broker 0
2019-01-25 12:11:00,711 Sending 1 messages to broker 0
2019-01-25 12:11:00,713 Successfully sent 1/1 messages to broker 2
2019-01-25 12:11:00,714 Fetched 3 messages for partition 0
2019-01-25 12:11:00,714 Partition 0 queue holds 3 messages
2019-01-25 12:11:00,714 Successfully sent 1/1 messages to broker 0
2019-01-25 12:11:00,717 Sending 1 messages to broker 0
2019-01-25 12:11:00,718 Sending 1 messages to broker 2
2019-01-25 12:11:00,720 Error encountered when producing to broker ip:9292. Retrying.
2019-01-25 12:11:00,720 Updating cluster, attempt 1/3
2019-01-25 12:11:00,722 Successfully sent 1/1 messages to broker 2
2019-01-25 12:11:00,722 Connecting to ip:9092
2019-01-25 12:11:00,722 Successfully sent 1/1 messages to broker 0
2019-01-25 12:11:00,722 Successfully connected to ip:9092
2019-01-25 12:11:00,726 RequestHandler.stop: about to flush requests queue
2019-01-25 12:11:00,728 Fetched 3 messages for partition 0
2019-01-25 12:11:00,728 Partition 0 queue holds 3 messages
2019-01-25 12:11:00,728 Discovered 3 brokers
2019-01-25 12:11:00,728 Broker ip:9092 metadata unchanged. Continuing.
2019-01-25 12:11:00,728 Broker ip:9192 metadata unchanged. Continuing.
2019-01-25 12:11:00,728 Reconnecting to broker id 2: ip:9292
2019-01-25 12:11:00,729 Connecting to ip:9292
2019-01-25 12:11:00,730 Successfully connected to ip:9292
2019-01-25 12:11:00,730 RequestHandler.stop: about to flush requests queue
2019-01-25 12:11:00,731 Discovered 16 topics
2019-01-25 12:11:00,731 Adding 1 partitions
2019-01-25 12:11:00,731 Starting new produce worker for broker 2
2019-01-25 12:11:00,731 Fetched 2 messages for partition 0
2019-01-25 12:11:00,731 Partition 0 queue holds 2 messages
2019-01-25 12:11:00,731 Successfully sent 0/1 messages to broker 2
2019-01-25 12:11:00,740 Sending 1 messages to broker 2
2019-01-25 12:11:00,740 Sending 1 messages to broker 0
2019-01-25 12:11:00,741 Sending 1 messages to broker 2

**Comment by emmett9001** [comment]
Thanks for the report, @rubinatorz. One thing I'd recommend trying is adjusting the `required_acks` kwarg on `get_producer` to be greater than 1. This setting controls the number of brokers that need to acknowledge the receipt of a message before it's considered persisted to the log. You might also try `stop`ing and `start`ing your producer immediately before calls to `produce` if you anticipate large gaps of time between bursts of message production.

**Comment by rubinatorz** [comment]
Hi @emmett9001 

Thanks you for thinking along! I tried the required_acks=2 but unfortunately I'm getting a direct error on producer.produce:

Traceback (most recent call last):
  File "/home/xxx/Test/Kafka/pure_producer.py", line 103, in <module>
    p.start(json_data)
  File "/home/xxx/Test/Kafka/pure_producer.py", line 40, in start
    self._producer.produce(simplejson.dumps(json_data))
  File "/usr/local/lib/python2.7/dist-packages/pykafka/producer.py", line 255, in __exit__
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/pykafka/producer.py", line 331, in stop
    stop_owned_brokers()
  File "/usr/local/lib/python2.7/dist-packages/pykafka/producer.py", line 324, in stop_owned_brokers
    self._wait_all()
  File "/usr/local/lib/python2.7/dist-packages/pykafka/producer.py", line 567, in _wait_all
    self._raise_worker_exceptions()
  File "/usr/local/lib/python2.7/dist-packages/pykafka/producer.py", line 240, in _raise_worker_exceptions
    reraise(*self._worker_exception)
  File "/usr/local/lib/python2.7/dist-packages/pykafka/producer.py", line 621, in queue_reader
    self.producer._send_request(batch, self)
  File "/usr/local/lib/python2.7/dist-packages/pykafka/producer.py", line 521, in _send_request
    exc = ERROR_CODES[presponse.err](info)
KeyError: 21

But thinking about my main issue (loosing messages)... It's seems strange that sync-producer gets all the messages produced successfully, while the async-producer looses some at the beginning of the batch. It certainly has to do with the producer loosing a connection in 20-30 minutes inactivity of the producer. But looking at the pykafka code, a mechanism looks in place to_retry sending lessages after a connection loss. And this doesn't seems to happen. So I could fix this by stopping and starting the producer... but it doesn't solve the real issue. Loosing a connection could also happen by accident and then the async-producer shouldn't loose messages neither.

I'm very willing to help you giving the right information, but I'm not a pykafka expert. I tried to understand the code behind producing, but it's a bit complex. So may be you can give me some hints on giving you the right information to pinpoint the problem.

Thanks!

**Comment by rubinatorz** [comment]
hi @emmett9001, do you maybe have a little bit of time to look into my last comment? Can I help in getting the right information for you to analyse this issue?

**Comment by emmett9001** [comment]
Looks like I gave you some wrong advice. Looking more closely at the Kafka protocol documentation, `2` is not a valid value for `required_acks` on produce requests. It can [only be](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-ProduceRequest) 1, -1, or 0. It looks like -1 is what you might want in this case.

As for the issue you're noticing with the asynchronous producer, I agree that it looks a lot like a real bug in the python implementation. I personally don't have the bandwidth to dig into it, but I'll keep this ticket open for reference in case a community member wants to look into it.

**Comment by carsonip** [comment]
Hi @rubinatorz, are you using any compression? e.g. lz4? Can you provide the code that you created the producer?

**Comment by rubinatorz** [comment]
hi @carsonip Nope, not using any compression. I'm setting up a KafkaClient object:

client = KafkaClient(hosts='my cluster', broker_version='1.1.0', ssl_config=None)

Next step is getting a Producer object from the topic list:

p = client.topics[topic_name].get_producer(min_queued_messages=1, linger_ms=5, delivery_reports=True, compression=0, use_rdkafka=False, sync=True)

And then calling:

producer.produce(msg, timestamp=datetime.now())

Any ideas on the cause or having the same problem?

**Comment by carsonip** [comment]
The last time I got an error like this, since the error was unknown to the client side (pykafka), it was easier for me to look at the logs of kafka and find out the exact error happened in kafka that caused the problematic response.

**Comment by carsonip** [comment]
@rubinatorz Sorry I misunderstood the issue earlier today. It would still be useful if you check if there are any errors on the kafka's side.
I would try to reproduce the issue when I have time. Also, is there a firewall / NAT or anything that triggered the disconnection? It would help to reproduce the issue.
