### ISSUE TITLE
Incompatible LZ4 compression causes error in Kafka and fails the delivery

### ISSUE THREAD

**Issue by carsonip** [Parsely/pykafka#914]
**PyKafka version**: 2.8.0
**Kafka version**: 2.0.1

Error in application (in stderr):
```
ERROR:pykafka.producer:Message not delivered!! UnknownError('Produce request for my-topic/5 to 127.0.0.1:31092 failed with error code -1.',)
```

Error in kafka:
```
[2019-02-11 04:39:56,320] ERROR [ReplicaManager broker=0] Error processing append operation on partition my-topic-0 (kafka.server.ReplicaManager)
org.apache.kafka.common.KafkaException: java.lang.RuntimeException: Dependent block stream is unsupported
    at org.apache.kafka.common.record.CompressionType$4.wrapForInput(CompressionType.java:113)
    at org.apache.kafka.common.record.AbstractLegacyRecordBatch$DeepRecordsIterator.<init>(AbstractLegacyRecordBatch.java:330)
    at org.apache.kafka.common.record.AbstractLegacyRecordBatch$DeepRecordsIterator.<init>(AbstractLegacyRecordBatch.java:310)
    at org.apache.kafka.common.record.AbstractLegacyRecordBatch.iterator(AbstractLegacyRecordBatch.java:232)
    at org.apache.kafka.common.record.AbstractLegacyRecordBatch.iterator(AbstractLegacyRecordBatch.java:227)
    at scala.collection.convert.Wrappers$JIterableWrapper.iterator(Wrappers.scala:54)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at kafka.log.LogValidator$$anonfun$validateMessagesAndAssignOffsetsCompressed$1.apply(LogValidator.scala:267)
    at kafka.log.LogValidator$$anonfun$validateMessagesAndAssignOffsetsCompressed$1.apply(LogValidator.scala:259)
    at scala.collection.Iterator$class.foreach(Iterator.scala:891)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at kafka.log.LogValidator$.validateMessagesAndAssignOffsetsCompressed(LogValidator.scala:259)
    at kafka.log.LogValidator$.validateMessagesAndAssignOffsets(LogValidator.scala:70)
    at kafka.log.Log$$anonfun$append$2.liftedTree1$1(Log.scala:771)
    at kafka.log.Log$$anonfun$append$2.apply(Log.scala:770)
    at kafka.log.Log$$anonfun$append$2.apply(Log.scala:752)
    at kafka.log.Log.maybeHandleIOException(Log.scala:1842)
    at kafka.log.Log.append(Log.scala:752)
    at kafka.log.Log.appendAsLeader(Log.scala:722)
    at kafka.cluster.Partition$$anonfun$13.apply(Partition.scala:660)
    at kafka.cluster.Partition$$anonfun$13.apply(Partition.scala:648)
    at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
    at kafka.utils.CoreUtils$.inReadLock(CoreUtils.scala:257)
    at kafka.cluster.Partition.appendRecordsToLeader(Partition.scala:647)
    at kafka.server.ReplicaManager$$anonfun$appendToLocalLog$2.apply(ReplicaManager.scala:745)
    at kafka.server.ReplicaManager$$anonfun$appendToLocalLog$2.apply(ReplicaManager.scala:733)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:733)
    at kafka.server.ReplicaManager.appendRecords(ReplicaManager.scala:471)
    at kafka.server.KafkaApis.handleProduceRequest(KafkaApis.scala:489)
    at kafka.server.KafkaApis.handle(KafkaApis.scala:113)
    at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:69)
    at java.lang.Thread.run(Thread.java:748)
```

My best guess is that something is wrong with the LZ4 compression in producer. I am producing a lot of messages in batch with async producer and this is reproducible. I'll have to move away from lz4 in the meantime.

**Comment by carsonip** [comment]
After digging around in #735, I found that the lz4 support PR creator @sghaskell wrote:
> I would imagine any simple tests you write will pass without setting block_mode. I found that I had to set it when producing messages due to a lack of support for dependent-block compression.
>
> See [KIP-57](https://cwiki.apache.org/confluence/display/KAFKA/KIP-57+-+Interoperable+LZ4+Framing)
>
> * The only flag left unsupported is dependent-block compression (LZ4 Stream API), which our implementation does not currently support.

I assume it is highly related to this issue. The implementation of kafka-python has changed to fix this. Please see https://github.com/dpkp/kafka-python/blob/eed59ba3b3c8800859572db046f36b5d8bd66487/kafka/codec.py#L22

**Comment by carsonip** [comment]
I have created a PR identical to kafka-python's fix. Please see #915.

**Comment by carsonip** [comment]
I have tried this fix in my environment and it works. I'll try to add some tests if I have time.

**Comment by emmett9001** [comment]
Adding tests for this would be great. Thanks @carsonip.

**Comment by carsonip** [comment]
I looked at pykafka's tests, the compression tests are simply compress then decompress, which is nice but cannot test this problem. This is about pykafka generating lz4 formats that Kafka doesn't accept. We either have to try producing the message to Kafka or dig into the bits and bytes of the compressed format. I'd go for the 1st approach. I'll produce and consume compressed messages in a new test file.

**Comment by carsonip** [comment]
I've added a test to producer's integration tests. It is confirmed that the test fails before the fix.

I've also added a dependency to `parameterized` library for parameterizing the test method with different compression types. Please let me know if you are okay with that / you have a better solution.

I saw that you had issues with PyPy and snappy with large message compression. I don't have the environment for that so it is uncertain whether the new test will pass in that specific environment.

**Comment by carsonip** [comment]
PR #915 merged. This issue can be closed.
